# Book settings
title: DSCI 551 - Descriptive Statistics and Probability for Data Science
author: Vincenzo Coia, Mike Gelbart, Aaron Berk, G. Alexi Rodríguez-Arelis, Katie Burak, and Vincent Liu
copyright: "2024"  # Copyright year to be placed in the footer
logo: notes/img/UBC_MDS_logo.png
exclude_patterns: ["archive/*", "source/*", "release/*", "lectures/teacher*"]

repository:
 url: https://github.com/UBC-MDS/DSCI_551_stat-prob-dsci

latex:
  latex_documents:
    targetname: book.tex

# Execution settings
execute:
  execute_notebooks         : "force"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")

# HTML-specific settings
html:
  favicon                   : ""  # A path to a favicon image
  navbar_number_sections    : false  # Add a number to each section in your left navbar
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  grid:
      sidebar-width: 300px
      body-width: 1800px
      margin-width: 350px
      gutter-width: 1.5em
parse:
  myst_enable_extensions:
    - html_image
    - dollarmath
sphinx:
  extra_extensions:
    - sphinx_exercise
