<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.53">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Lecture 3: Joint Probability – DSCI 551: Descriptive Statistics and Probability for Data Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notes/04_lecture-conditional.html" rel="next">
<link href="../notes/02_lecture-parametric-families.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style>html{ scroll-behavior: smooth; }</style>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script><link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../styles.css">
</head>
<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">DSCI 551: Descriptive Statistics and Probability for Data Science</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
<ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item compact">
    <a class="nav-link" href="https://github.com/UBC-MDS/DSCI_551_stat-prob-dsci"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../learning-goals.html">Lectures</a></li><li class="breadcrumb-item"><a href="../notes/03_lecture-joint.html">Lecture 3: Joint Probability</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../notes/img/UBC_MDS_logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none"></a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Lectures</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../learning-goals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learning Goals by Lecture</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/01_lecture-uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 1: Depicting Uncertainty</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/02_lecture-parametric-families.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 2: Parametric Families</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/03_lecture-joint.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Lecture 3: Joint Probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/04_lecture-conditional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 4: Conditional Probabilities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/05_lecture-continuous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 5: Continuous Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/06_lecture-continuous-families.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 6: Common Distribution Families and Conditioning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/07_lecture-maximum-likelihood-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 7: Maximum Likelihood Estimation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/08_lecture-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 8: Simulation</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/appendix-prob-cheatsheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability Cheatsheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/appendix-dist-cheatsheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Distribution Cheatsheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/appendix-greek-alphabet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Greek Alphabet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../LICENSE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">License</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="4"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#slides" id="toc-slides" class="nav-link active" data-scroll-target="#slides"><span class="header-section-number">1</span> Slides</a></li>
  <li><a href="#learning-goals" id="toc-learning-goals" class="nav-link" data-scroll-target="#learning-goals"><span class="header-section-number">2</span> Learning Goals</a></li>
  <li>
<a href="#joint-distributions" id="toc-joint-distributions" class="nav-link" data-scroll-target="#joint-distributions"><span class="header-section-number">3</span> Joint Distributions</a>
  <ul>
<li><a href="#example-length-of-stay-versus-gang-demand" id="toc-example-length-of-stay-versus-gang-demand" class="nav-link" data-scroll-target="#example-length-of-stay-versus-gang-demand"><span class="header-section-number">3.1</span> Example: Length of Stay Versus Gang Demand</a></li>
  <li><a href="#calculating-marginal-distributions-from-the-joint-distribution" id="toc-calculating-marginal-distributions-from-the-joint-distribution" class="nav-link" data-scroll-target="#calculating-marginal-distributions-from-the-joint-distribution"><span class="header-section-number">3.2</span> Calculating Marginal Distributions from the Joint Distribution</a></li>
  </ul>
</li>
  <li>
<a href="#independence-and-dependence-concepts" id="toc-independence-and-dependence-concepts" class="nav-link" data-scroll-target="#independence-and-dependence-concepts"><span class="header-section-number">4</span> Independence and Dependence Concepts</a>
  <ul>
<li><a href="#independence" id="toc-independence" class="nav-link" data-scroll-target="#independence"><span class="header-section-number">4.1</span> Independence</a></li>
  <li>
<a href="#measures-of-dependence" id="toc-measures-of-dependence" class="nav-link" data-scroll-target="#measures-of-dependence"><span class="header-section-number">4.2</span> Measures of Dependence</a>
  <ul class="collapse">
<li><a href="#covariance-and-pearsons-correlation" id="toc-covariance-and-pearsons-correlation" class="nav-link" data-scroll-target="#covariance-and-pearsons-correlation"><span class="header-section-number">4.2.1</span> Covariance and Pearson’s Correlation</a></li>
  <li><a href="#kendalls-tau_k" id="toc-kendalls-tau_k" class="nav-link" data-scroll-target="#kendalls-tau_k"><span class="header-section-number">4.2.2</span> Kendall’s <span class="math inline">\(\tau_K\)</span></a></li>
  <li><a href="#optional-mutual-information" id="toc-optional-mutual-information" class="nav-link" data-scroll-target="#optional-mutual-information"><span class="header-section-number">4.2.3</span> (Optional) Mutual Information</a></li>
  </ul>
</li>
  <li><a href="#variance-of-a-sum-involving-two-non-independent-random-variables" id="toc-variance-of-a-sum-involving-two-non-independent-random-variables" class="nav-link" data-scroll-target="#variance-of-a-sum-involving-two-non-independent-random-variables"><span class="header-section-number">4.3</span> Variance of a Sum Involving Two Non-Independent Random Variables</a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/UBC-MDS/DSCI_551_stat-prob-dsci/issues" class="toc-action"><i class="bi bi-chat-right"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../learning-goals.html">Lectures</a></li><li class="breadcrumb-item"><a href="../notes/03_lecture-joint.html">Lecture 3: Joint Probability</a></li></ol></nav><div class="quarto-title">
<h1 class="title">Lecture 3: Joint Probability</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="slides" class="level2" data-number="1"><h2 data-number="1" class="anchored" data-anchor-id="slides">
<span class="header-section-number">1</span> Slides</h2>
<iframe src="../slides/03_lecture-joint/03_lecture-joint.html" width="100%" height="600px" style="border: none;">
</iframe>
</section><section id="learning-goals" class="level2" data-number="2"><h2 data-number="2" class="anchored" data-anchor-id="learning-goals">
<span class="header-section-number">2</span> Learning Goals</h2>
<p>By the end of this lecture, you should be able to:</p>
<ul>
<li>Calculate marginal distributions from a joint distribution of random variables.</li>
<li>Describe the probabilistic consequences of working with independent random variables.</li>
<li>Calculate and describe covariance in multivariate cases (i.e., with more than one random variable).</li>
<li>Calculate and describe two mainstream correlation metrics: Pearson’s correlation and Kendall’s <span class="math inline">\(\tau_K\)</span>.</li>
</ul></section><section id="joint-distributions" class="level2" data-number="3"><h2 data-number="3" class="anchored" data-anchor-id="joint-distributions">
<span class="header-section-number">3</span> Joint Distributions</h2>
<p>This lecture will explore cases simultaneously involving multiple random variables. Hence, let us begin with the concept of <strong>joint distribution</strong>. So far, we have only considered one random variable at a time. Its distribution is called <strong>univariate</strong> because there is just one variable. However, we very often have more than one random variable.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition of Joint Distribution
</div>
</div>
<div class="callout-body-container callout-body">
<p>A joint distribution is a formal probability distribution involving two or more simultaneous random variables, either discrete or continuous, in a random process or system. This joint distribution has to encompass all possible outcomes for these two or more random variables.</p>
</div>
</div>
<div id="fig-two-coins" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-two-coins-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/two_coins.png" class="img-fluid figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-coins-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Two coins.
</figcaption></figure>
</div>
<p>Let us start with an example involving coin tosses. Thus, consider <strong>two independent fair coins</strong> with two possible outcomes each: heads (<span class="math inline">\(\text{H}\)</span>) or tails (<span class="math inline">\(\text{T}\)</span>). The possible <strong>joint outcomes</strong> (<strong>where the outcome order matters</strong>) are: <span class="math inline">\(\texttt{HH}\)</span>, <span class="math inline">\(\texttt{HT}\)</span>, <span class="math inline">\(\texttt{TH}\)</span>, <span class="math inline">\(\texttt{TT}\)</span>, each with a probability <span class="math inline">\(0.25\)</span>. We can visualize this as a joint distribution in <a href="#tbl-joint-dist-coins" class="quarto-xref">Table&nbsp;1</a>.</p>
<div id="tbl-joint-dist-coins" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-joint-dist-coins-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Joint probability distribution of two independent coin tosses.
</figcaption><div aria-describedby="tbl-joint-dist-coins-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(X/Y\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\texttt{H}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\texttt{T}\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\texttt{H}\)</span></td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\texttt{T}\)</span></td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.25</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Note that an outcome in <a href="#tbl-joint-dist-coins" class="quarto-xref">Table&nbsp;1</a> consists of a pair of values. The sum of all probabilities still adds to 1 since this is <strong>proper</strong> a probability distribution. Moreover, we could set the following <strong>binary random variables</strong> (since each one could only have two outcomes, <span class="math inline">\(\texttt{H}\)</span> or <span class="math inline">\(\texttt{T}\)</span>):</p>
<p><span class="math display">\[
\begin{gather*}
X = \text{First coin's outcome.} \\
Y = \text{Second coin's outcome.}
\end{gather*}
\]</span></p>
<p>Therefore, for example via the independence property, one cell from <a href="#tbl-joint-dist-coins" class="quarto-xref">Table&nbsp;1</a> can be written as:</p>
<p> </p>
<p><span class="math display">\[
\begin{align*}
P(X = \texttt{H} \cap Y = \texttt{H}) &amp;= P(X = \texttt{H}) \cdot P(Y = \texttt{H}) \qquad \text{since both tosses are independent} \\
&amp;= 0.5 \cdot 0.5 \qquad \text{ both coins are fair} \\
&amp;= 0.25.
\end{align*}
\]</span></p>
<p>Note this is not really any different from what we have already seen. We can still write this as an <strong>univariate distribution with four outcomes</strong>. This is useful to remember when we are calculating probabilities. Thus, alternatively, we can define the following random variable:</p>
<p><span class="math display">\[Z = \text{Outcomes obtained when tossing two independent coins,}\]</span></p>
<p>whose probability mass function (PMF) is shown in <a href="#tbl-pmf-z-coins" class="quarto-xref">Table&nbsp;2</a>.</p>
<div id="tbl-pmf-z-coins" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pmf-z-coins-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Probability mass function of random variable <span class="math inline">\(Z\)</span> for two independent coin tosses.
</figcaption><div aria-describedby="tbl-pmf-z-coins-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(Z\)</span></th>
<th style="text-align: center;">Probability</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\texttt{HH}\)</span></td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\texttt{HT}\)</span></td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\texttt{TH}\)</span></td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\texttt{TT}\)</span></td>
<td style="text-align: center;">0.25</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The PMF of <span class="math inline">\(Z\)</span> in <a href="#tbl-pmf-z-coins" class="quarto-xref">Table&nbsp;2</a> considers the order in which we obtain the outcomes.</p>
</div>
</div>
<p>Viewing the distribution in <a href="#tbl-joint-dist-coins" class="quarto-xref">Table&nbsp;1</a> as a (2-dimensional) matrix, instead of a (1-dimensional) vector as in <a href="#tbl-pmf-z-coins" class="quarto-xref">Table&nbsp;2</a>, is more useful when determining the properties of individual random variables. Thus, in practice, many cases will require multivariate distributions.</p>
<section id="example-length-of-stay-versus-gang-demand" class="level3" data-number="3.1"><h3 data-number="3.1" class="anchored" data-anchor-id="example-length-of-stay-versus-gang-demand">
<span class="header-section-number">3.1</span> Example: Length of Stay Versus Gang Demand</h3>
<p>Throughout this lecture, we will work with the following joint distribution of <strong>length of stay</strong> of a ship and its <strong>gang demand</strong>.</p>
<div id="fig-cargo-ship" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-cargo-ship-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ship.png" class="img-fluid figure-img" width="650">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cargo-ship-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: A cargo ship.
</figcaption></figure>
</div>
<p>Consider an example that a Vancouver port faces with “<em>gang demand</em>.” Whenever a ship arrives at the port of Vancouver, they request a certain number of “<em>gangs</em>” (groups of people) to help unload the ship. Let us suppose the number of <span class="math inline">\(\text{Gangs}\)</span> requested by a ship has the following PMF:</p>
<div class="cell">
<div id="tbl-pmf-gangs" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pmf-gangs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Probability mass function for the number of Gangs.
</figcaption><div aria-describedby="tbl-pmf-gangs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: center;">Number of Gangs</th>
<th style="text-align: center;">Probability</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.2</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.3</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.1</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Furthermore, each ship will stay at port for a random number of days, which is the length of stay (<span class="math inline">\(\text{LOS}\)</span>), according to the following distribution:</p>
<div class="cell">
<div id="tbl-pmf-los" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pmf-los-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Probability mass function for the length of stay (LOS) in days.
</figcaption><div aria-describedby="tbl-pmf-los-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: center;">Length of Stay (LOS) in Days</th>
<th style="text-align: center;">Probability</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.35</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.20</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">0.10</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The above PMF can be conveyed as a plot, table, or mathematical function; all options are correct. There is no significance (not statistically speaking!).</p>
</div>
</div>
<p>Given the above information coming from the PMF for <span class="math inline">\(\text{LOS}\)</span>, here is a question we might be interested in:</p>
<blockquote class="blockquote">
<p>What is the probability that a ship requires 4 gangs <strong>AND</strong> will stay in port for 5 days?</p>
</blockquote>
<p>There is some bad news here. First, the information provided by both separate PMFs (<span class="math inline">\(\text{Gangs}\)</span> and <span class="math inline">\(\text{LOS}\)</span>) is not sufficient to answer this question.</p>
<p>Of course, there is a 10% chance of needing 4 gangs <strong>in the absence of other information</strong>, and a 10% chance of staying for 5 days <strong>in the absence of other information</strong>. We could try multiplying these numbers together, giving us 1%, <strong>if we assume independence (which might not be the case here as explained further!)</strong>. Hence, what if more extended stays require fewer gangs because there is more time to do the work? In that case, it might be extremely unlikely to find the combination of needed 4 gangs and stay for 5 days: perhaps 0.1% or lower. Or maybe something else is going on, and the probability is higher than 1%! Who knows?</p>
<p>In this and the following lecture, we will focus on these types of questions. Specifically, this lecture will focus on the question above (<strong>4 gangs AND 5 days</strong>), and the next lecture will focus on a slightly different question:</p>
<blockquote class="blockquote">
<p><strong>IF</strong> you already know that the length of stay is 5 days, what is the probability of needing 4 gangs?</p>
</blockquote>
<p>For now, let us proceed with joint distributions. Above, we have the PMFs for the number of <span class="math inline">\(\text{Gangs}\)</span> and <span class="math inline">\(\text{LOS}\)</span> <strong>individually</strong>. Formally, these individual distributions are called <strong>marginal distributions</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition of Marginal Distribution
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>In a random system/process with more than one random variable</strong>, the distribution of a standalone variable is called marginal distribution (sometimes just “<em>marginal</em>” or “<em>margin</em>”).</p>
<p>We use the word “marginal” to emphasize that the distribution is being considered <strong>in isolation</strong> from other related variables in the same random process or system.</p>
</div>
</div>
<p>Since we have 4 possibilities for the number of <span class="math inline">\(\text{Gangs}\)</span>, we have 4 probabilities that add up to 1; and since we have 5 possibilities for <span class="math inline">\(\text{LOS}\)</span>, we have 5 probabilities that add up to 1. But these 9 probabilities do not tell the whole story. So, how many do we need? We need a probability for <strong>every possible combination</strong> of the number of <span class="math inline">\(\text{LOS}\)</span> and <span class="math inline">\(\text{Gangs}\)</span>. In this case, <span class="math inline">\(5 \times 4 = 20\)</span> probabilities (that again add up to 1). We might display these 20 probabilities in a <span class="math inline">\(5 \times 4\)</span> joint probability table:</p>
<div id="tbl-joint-pmg-gangs-los" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-joint-pmg-gangs-los-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Joint probability mass function for the number of Gangs and length of stay (LOS) in days.
</figcaption><div aria-describedby="tbl-joint-pmg-gangs-los-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="sourceCode anchored" id="tbl-joint-pmg-gangs-los"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">joint_distribution</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</figure>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Gangs = 1</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Gangs = 2</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Gangs = 3</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Gangs = 4</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 1</td>
<td style="text-align: center;">0.00170</td>
<td style="text-align: center;">0.04253</td>
<td style="text-align: center;">0.12471</td>
<td style="text-align: center;">0.08106</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 2</td>
<td style="text-align: center;">0.02664</td>
<td style="text-align: center;">0.16981</td>
<td style="text-align: center;">0.13598</td>
<td style="text-align: center;">0.01757</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 3</td>
<td style="text-align: center;">0.05109</td>
<td style="text-align: center;">0.11563</td>
<td style="text-align: center;">0.03203</td>
<td style="text-align: center;">0.00125</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 4</td>
<td style="text-align: center;">0.04653</td>
<td style="text-align: center;">0.04744</td>
<td style="text-align: center;">0.00593</td>
<td style="text-align: center;">0.00010</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 5</td>
<td style="text-align: center;">0.07404</td>
<td style="text-align: center;">0.02459</td>
<td style="text-align: center;">0.00135</td>
<td style="text-align: center;">0.00002</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We can make sure these probabilities add up to 1 via the function <code><a href="https://rdrr.io/r/base/sum.html">sum()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">joint_distribution</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Going from the initial marginal distributions to the joint distribution is not a straightforward procedure. It requires more advanced statistical techniques. Specifically, in this case, we use a <strong>Gaussian copula</strong>, which is common in risk management.</p>
<p>Roughly speaking, a copula allows us to understand the dependency structure in a multivariate random system or process in which the marginal distributions play a crucial role. Since the construction of joint distributions via copulas is out of the scope of this course, we will use the resulting <code>joint_distribution</code> “<em>as is</em>” to illustrate this lecture’s concepts.</p>
</div>
</div>
<p>Moving along with the corresponding joint distribution, we can see the probability of needing 4 <span class="math inline">\(\text{Gangs}\)</span> and <span class="math inline">\(\text{LOS}\)</span> of 5 days is less than 1% in this case, i.e.:</p>
<p><span class="math display">\[P(\text{LOS} = 5 \cap \text{Gangs} = 4) = 0.00002.\]</span></p>
<p>Now, we might wonder:</p>
<blockquote class="blockquote">
<p>Could the 20 numbers in the matrix <code>joint_distribution</code> be absolutely <strong>ANY</strong> probabilities between 0 and 1?</p>
</blockquote>
<p>No, they cannot be any probability between 0 and 1. They are restricted by the fact that they will need to add up to 1 (recall the Law of Total Probability!). Furthermore, there are other restrictions:</p>
<ul>
<li>We already specified the marginal distributions of the number of <span class="math inline">\(\text{Gangs}\)</span> and <span class="math inline">\(\text{LOS}\)</span> earlier. Therefore, we need the joint distribution above to be consistent with those marginal distributions (otherwise, we would likely break the probability rules from the first lecture).</li>
<li>If we already said the <strong>marginal probability</strong> of needing 4 <span class="math inline">\(\text{Gangs}\)</span> is 10%, the joint distribution <strong>should not contradict that information</strong> or something would be wrong. This is why multivariate methods such as a Gaussian copula are used to reflect this class of facts.</li>
</ul></section><section id="calculating-marginal-distributions-from-the-joint-distribution" class="level3" data-number="3.2"><h3 data-number="3.2" class="anchored" data-anchor-id="calculating-marginal-distributions-from-the-joint-distribution">
<span class="header-section-number">3.2</span> Calculating Marginal Distributions from the Joint Distribution</h3>
<p>We have just specified a joint distribution of <span class="math inline">\(\text{LOS}\)</span> and <span class="math inline">\(\text{Gangs}\)</span>. But, beforehand, we specified a distribution for these variables individually. Therefore:</p>
<ul>
<li>If you have a joint distribution, then the marginal distribution of each individual variable follows as a consequence.</li>
<li>If you have the marginal distribution of each individual variable, you still do not have enough information to form the joint distribution between the variables.</li>
</ul>
<p>In the case of discrete random variables, such as in our cargo ship example, calculating a marginal distribution involves adding up the probabilities corresponding to standalone outcomes of <span class="math inline">\(\text{LOS}\)</span> and <span class="math inline">\(\text{Gangs}\)</span>.</p>
<p>Let us start with the marginal distribution of <span class="math inline">\(\text{LOS}\)</span>. Thus, using our <code>joint_distribution</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">joint_distribution</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Gangs = 1</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Gangs = 2</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Gangs = 3</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Gangs = 4</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 1</td>
<td style="text-align: center;">0.00170</td>
<td style="text-align: center;">0.04253</td>
<td style="text-align: center;">0.12471</td>
<td style="text-align: center;">0.08106</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 2</td>
<td style="text-align: center;">0.02664</td>
<td style="text-align: center;">0.16981</td>
<td style="text-align: center;">0.13598</td>
<td style="text-align: center;">0.01757</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 3</td>
<td style="text-align: center;">0.05109</td>
<td style="text-align: center;">0.11563</td>
<td style="text-align: center;">0.03203</td>
<td style="text-align: center;">0.00125</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 4</td>
<td style="text-align: center;">0.04653</td>
<td style="text-align: center;">0.04744</td>
<td style="text-align: center;">0.00593</td>
<td style="text-align: center;">0.00010</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 5</td>
<td style="text-align: center;">0.07404</td>
<td style="text-align: center;">0.02459</td>
<td style="text-align: center;">0.00135</td>
<td style="text-align: center;">0.00002</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now, we can compute <span class="math inline">\(P(\text{LOS} = 1)\)</span>. Thus, there are four ways this could happen:</p>
<ul>
<li>
<span class="math inline">\(\text{LOS} = 1\)</span> and <span class="math inline">\(\text{Gangs} = 1\)</span>.</li>
<li>
<span class="math inline">\(\text{LOS} = 1\)</span> and <span class="math inline">\(\text{Gangs} = 2\)</span>.</li>
<li>
<span class="math inline">\(\text{LOS} = 1\)</span> and <span class="math inline">\(\text{Gangs} = 3\)</span>.</li>
<li>
<span class="math inline">\(\text{LOS} = 1\)</span> and <span class="math inline">\(\text{Gangs} = 4\)</span>.</li>
</ul>
<p>So, to find the marginal probability <span class="math inline">\(P(\text{LOS} = 1)\)</span>, we need to add up those four joint probabilities. Looking at our <code>joint_distribution</code> of <span class="math inline">\(\text{LOS}\)</span> and <span class="math inline">\(\text{Gangs}\)</span>, this corresponds to summing the first row of the joint probability table.</p>
<p><span class="math display">\[
\begin{align*}
P(\text{LOS} = 1) &amp;= P(\text{LOS} = 1 \cap \text{Gangs} = 1) + P(\text{LOS} = 1 \cap \text{Gangs} = 2) + \\
&amp; \qquad P(\text{LOS} = 1 \cap \text{Gangs} = 3) + P(\text{LOS} = 1 \cap \text{Gangs} = 4) \\
&amp;= 0.00170 + 0.04253 + 0.12471 + 0.08106 \\
&amp;= 0.25.
\end{align*}
\]</span></p>
<p>We have <span class="math inline">\(P(\text{LOS} = 1)\)</span>, but we would also need <span class="math inline">\(P(\text{LOS} = 2)\)</span>, <span class="math inline">\(P(\text{LOS} = 3)\)</span>, <span class="math inline">\(P(\text{LOS} = 4)\)</span>, and <span class="math inline">\(P(\text{LOS} = 5)\)</span>. It follows that the marginal distribution of <span class="math inline">\(\text{LOS}\)</span> can be obtained by adding up each row in our <code>joint_distribution</code> (we use the function <code><a href="https://rdrr.io/r/base/colSums.html">rowSums()</a></code>).</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="va">joint_distribution</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Probability</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 1</td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 2</td>
<td style="text-align: center;">0.35</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 3</td>
<td style="text-align: center;">0.20</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 4</td>
<td style="text-align: center;">0.10</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 5</td>
<td style="text-align: center;">0.10</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Note that the distribution of <span class="math inline">\(\text{LOS}\)</span> is the same we had at the beginning of the lecture. Hence, our <code>joint_distribution</code> is <strong>consistent</strong> with the initial marginal distribution of <span class="math inline">\(\text{LOS}\)</span>.</p>
<p>Analogously, the marginal distribution of <span class="math inline">\(\text{Gangs}\)</span> can be obtained by summing the columns from our <code>joint_distribution</code> (we use function <code><a href="https://rdrr.io/r/base/colSums.html">colSums()</a></code>):</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span><span class="op">(</span><span class="va">joint_distribution</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Probability</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">Gangs = 1</td>
<td style="text-align: center;">0.2</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">Gangs = 2</td>
<td style="text-align: center;">0.4</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">Gangs = 3</td>
<td style="text-align: center;">0.3</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">Gangs = 4</td>
<td style="text-align: center;">0.1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Also, the marginal distribution of <span class="math inline">\(\text{Gangs}\)</span> is the same we had at the beginning of the lecture. Thus, our <code>joint_distribution</code> is <strong>consistent</strong> with the initial marginal distribution of <span class="math inline">\(\text{Gangs}\)</span>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is crucial to highlight that there is more than one way to obtain a joint distribution. Any specific procedure will depend on factors such as the existing correlation between a given set of random variables.</p>
</div>
</div>
<p>Now, we will start with in-class questions via <a href="https://student.iclicker.com/"><strong>iClicker</strong></a>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 14
</div>
</div>
<div class="callout-body-container callout-body">
<p>Answer <strong>TRUE</strong> or <strong>FALSE</strong>:</p>
<p>We obtain a marginal distribution by summing the rows of a joint distribution; therefore, each row of a joint distribution must sum to 1.</p>
<p><strong>A.</strong> TRUE</p>
<p><strong>B.</strong> FALSE</p>
</div>
</div>
</section></section><section id="independence-and-dependence-concepts" class="level2" data-number="4"><h2 data-number="4" class="anchored" data-anchor-id="independence-and-dependence-concepts">
<span class="header-section-number">4</span> Independence and Dependence Concepts</h2>
<p>In practice, a big part of Data Science is about harvesting the relationship between the variables in our datasets. For instance, we might be interested in inferring what factors influence leisure expenditure in Canadian households with similar sociodemographic profiles (i.e., there might be some data <strong>dependence</strong>). Or maybe, what factors influence leisure expenditure in Canadian households with totally different sociodemographic profiles (i.e., there might be some data <strong>independence</strong>).</p>
<section id="independence" class="level3" data-number="4.1"><h3 data-number="4.1" class="anchored" data-anchor-id="independence">
<span class="header-section-number">4.1</span> Independence</h3>
<p>Let <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> be two random variables. Retaking the concept of independent events, we say <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are <strong>independent</strong> if knowing something about one of them tells us nothing about the other. Analogous to the independence equation, a definition of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> being independent is the following:</p>
<p><span class="math display">\[P(X = x \cap Y = y) = P(X = x) \cdot P(Y = y), \text{for all } x \text{ and } y.\]</span></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>What does this equation tell us about a <strong>hypothetical joint probability table</strong> whose cells are <span class="math inline">\(P(X = x \cap Y = y)\)</span>?</p>
<p>Well, <strong>if <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent</strong>, we do not actually need the whole table! Instead, we only need the marginals of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. Therefore, the full joint distribution between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is just the product of their respective marginal probabilities.</p>
</div>
</div>
<p>Note independence is not some property that you can specify separately from the joint PMF. Recall the joint PMF specifies everything about a given situation/process/system involving more than one random variable, including whether or not the random variables are independent.</p>
<p>Going back to our earlier example of two coin flips, recall we had this joint distribution:</p>
<p><span class="math display">\[
\begin{gather*}
X = \text{First coin's outcome.} \\
Y = \text{Second coin's outcome.}
\end{gather*}
\]</span></p>
<div id="tbl-joint-dist-coins-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-joint-dist-coins-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Joint probability distribution of two independent coin tosses.
</figcaption><div aria-describedby="tbl-joint-dist-coins-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(X/Y\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\texttt{H}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\texttt{T}\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\texttt{H}\)</span></td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\texttt{T}\)</span></td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.25</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>From the joint PMF in <a href="#tbl-joint-dist-coins-2" class="quarto-xref">Table&nbsp;6</a>, we can see that the two coin flips are independent. The marginals are the following:</p>
<p><span class="math display">\[
\begin{align*}
P(X = \texttt{H}) &amp;= P(X = \texttt{H} \cap Y = \texttt{H}) + P(X = \texttt{H} \cap Y = \texttt{T}) \\
&amp;= 0.25 + 0.25 \\
&amp;= 0.5.
\end{align*}
\]</span></p>
<p><span class="math display">\[
\begin{align*}
P(X = \texttt{T}) &amp;= P(X = \texttt{T} \cap Y = \texttt{H}) + P(X = \texttt{T} \cap Y = \texttt{T}) \\
&amp;= 0.25 + 0.25 \\
&amp;= 0.5.
\end{align*}
\]</span></p>
<p><span class="math display">\[
\begin{align*}
P(Y = \texttt{H}) &amp;= P(X = \texttt{H} \cap Y = \texttt{H}) + P(X = \texttt{T} \cap Y = \texttt{H}) \\
&amp;= 0.25 + 0.25 \\
&amp;= 0.5.
\end{align*}
\]</span></p>
<p><span class="math display">\[
\begin{align*}
P(Y = \texttt{T}) &amp;= P(X = \texttt{H} \cap Y = \texttt{T}) + P(X = \texttt{T} \cap Y = \texttt{T}) \\
&amp;= 0.25 + 0.25 \\
&amp;= 0.5.
\end{align*}
\]</span></p>
<p>Moreover, we have that:</p>
<p><span class="math display">\[
\begin{align*}
P(X = \texttt{H} \cap Y = \texttt{H}) &amp;= P(X = \texttt{H}) \cdot P(Y = \texttt{H}) \\
&amp;= 0.5 \cdot 0.5 \\
&amp;= 0.25.
\end{align*}
\]</span></p>
<p><span class="math display">\[
\begin{align*}
P(X = \texttt{H} \cap Y = \texttt{T}) &amp;= P(X = \texttt{H}) \cdot P(Y = \texttt{T}) \\
&amp;= 0.5 \cdot 0.5 \\
&amp;= 0.25.
\end{align*}
\]</span></p>
<p><span class="math display">\[
\begin{align*}
P(X = \texttt{T} \cap Y = \texttt{H}) &amp;= P(X = \texttt{T}) \cdot P(Y = \texttt{H}) \\
&amp;= 0.5 \cdot 0.5 \\
&amp;= 0.25.
\end{align*}
\]</span></p>
<p><span class="math display">\[
\begin{align*}
P(X = \texttt{T} \cap Y = \texttt{T}) &amp;= P(X = \texttt{T}) \cdot P(Y = \texttt{T}) \\
&amp;= 0.5 \cdot 0.5 \\
&amp;= 0.25.
\end{align*}
\]</span></p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The entire marginal distribution for a coin can be specified with a single number, e.g.,</p>
<p><span class="math display">\[P(X = \texttt{H}) = 0.5.\]</span></p>
<p>The reason for this is the Law of Total Probability in the case of a <strong>single random variable</strong>:</p>
<p><span class="math display">\[P(X = \texttt{H}) + P(X = \texttt{T}) = 1,\]</span></p>
<p>so</p>
<p><span class="math display">\[P(X = \texttt{T}) = 1 - P(X = \texttt{H})\]</span></p>
<p>When talking about <strong>degrees of freedom</strong>, it is actually best to account for this fact. Thus, each coin has 1 degree of freedom, and (in general) the joint of two coins has 3 because the Law of Total Probability fixes the fourth probability. More on this later in <em>DSCI 552</em>.</p>
</div>
</div>
<p>Now, let us explore a <strong>different two-coin example</strong>. How about the below PMF? Are the two coins independent?</p>
<div id="tbl-joint-dist-coins-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-joint-dist-coins-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Another joint probability distribution of two coin tosses.
</figcaption><div aria-describedby="tbl-joint-dist-coins-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(X/Y\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\texttt{H}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\texttt{T}\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\texttt{H}\)</span></td>
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">0.6</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\texttt{T}\)</span></td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.15</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>To answer this independence question, let us reflect the following:</p>
<blockquote class="blockquote">
<p>Can we come up with a value of <span class="math inline">\(P(X = \texttt{H})\)</span> and a value of <span class="math inline">\(P(Y = \texttt{H})\)</span> such that the joint probabilities match the above joint distribution?</p>
</blockquote>
<p>It turns out we can! Let us first compute the marginals. Here, we have:</p>
<p><span class="math display">\[
\begin{align*}
P(X = \texttt{H}) &amp;= P(X = \texttt{H} \cap Y = \texttt{H}) + P(X = \texttt{H} \cap Y = \texttt{T}) \\
&amp;= 0.2 + 0.6 \\
&amp;= 0.8.
\end{align*}
\]</span></p>
<p>By the Law of Total Probability, we can obtain:</p>
<p><span class="math display">\[
\begin{align*}
P(X = \texttt{T}) &amp;= 1 - P(X = \texttt{H})\\
&amp;= 1 - 0.8 \\
&amp;= 0.2.
\end{align*}
\]</span></p>
<p>And likewise for the second coin:</p>
<p><span class="math display">\[
\begin{align*}
P(Y = \texttt{H}) &amp;= P(X = \texttt{H} \cap Y = \texttt{H}) + P(X = \texttt{T} \cap Y = \texttt{H}) \\
&amp;= 0.2 + 0.05 \\
&amp;= 0.25.
\end{align*}
\]</span></p>
<p>And, by the Law of Total Probability, we have that:</p>
<p><span class="math display">\[
\begin{align*}
P(Y = \texttt{T}) &amp;= 1 - P(Y = \texttt{H})\\
&amp;= 1 - 0.25 \\
&amp;= 0.75.
\end{align*}
\]</span></p>
<p>Now, that last thing we need to do is check whether the joint distribution, from <a href="#tbl-joint-dist-coins-3" class="quarto-xref">Table&nbsp;7</a>, satisfies the definition of independence:</p>
<p><span class="math display">\[P(X = x \cap Y = y) = P(X = x) \cdot P(Y = y).\]</span></p>
<p><strong>If <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent</strong>, then the following computations will match <a href="#tbl-joint-dist-coins-3" class="quarto-xref">Table&nbsp;7</a>:</p>
<p><span class="math display">\[
\begin{align*}
P(X = \texttt{H} \cap Y = \texttt{H}) &amp;= P(X = \texttt{H}) \cdot P(Y = \texttt{H}) \\
&amp;= 0.8 \cdot 0.25 \\
&amp;= 0.2.
\end{align*}
\]</span></p>
<p><span class="math display">\[
\begin{align*}
P(X = \texttt{H} \cap Y = \texttt{T}) &amp;= P(X = \texttt{H}) \cdot P(Y = \texttt{T}) \\
&amp;= 0.8 \cdot 0.75 \\
&amp;= 0.6.
\end{align*}
\]</span></p>
<p><span class="math display">\[
\begin{align*}
P(X = \texttt{T} \cap Y = \texttt{H}) &amp;= P(X = \texttt{T}) \cdot P(Y = \texttt{H}) \\
&amp;= 0.2 \cdot 0.25 \\
&amp;= 0.05.
\end{align*}
\]</span></p>
<p><span class="math display">\[
\begin{align*}
P(X = \texttt{T} \cap Y = \texttt{T}) &amp;= P(X = \texttt{T}) \cdot P(Y = \texttt{T}) \\
&amp;= 0.2 \cdot 0.75  \\
&amp;= 0.15.
\end{align*}
\]</span></p>
<p>And so, we again see that the two coins from <a href="#tbl-joint-dist-coins-3" class="quarto-xref">Table&nbsp;7</a> are independent!</p>
<p>Finally, here is a quick example of two coins that are definitely <strong>NOT</strong> independent:</p>
<div id="tbl-joint-dist-coins-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-joint-dist-coins-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Another joint probability distribution of two coin tosses.
</figcaption><div aria-describedby="tbl-joint-dist-coins-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(X/Y\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\texttt{H}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\texttt{T}\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\texttt{H}\)</span></td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\texttt{T}\)</span></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.5</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>In <a href="#tbl-joint-dist-coins-4" class="quarto-xref">Table&nbsp;8</a>, the marginals are both 0.5 (the same marginals as our earlier example!), but the joint is not the product of the marginals. In fact, these two coins are <strong>completely dependent</strong>: if one is heads, then the other is always heads, and if one is tails then the other is always tails (<span class="math inline">\(\texttt{HT}\)</span> and <span class="math inline">\(\texttt{TH}\)</span> have probability zero).</p>
</section><section id="measures-of-dependence" class="level3" data-number="4.2"><h3 data-number="4.2" class="anchored" data-anchor-id="measures-of-dependence">
<span class="header-section-number">4.2</span> Measures of Dependence</h3>
<p>Next, if two random variables <strong>ARE NOT</strong> independent, how can we go about measuring the strength/amount of dependence between these two random variables? For example, if the two coins above are “completely dependent,” can we quantify this?</p>
<section id="covariance-and-pearsons-correlation" class="level4" data-number="4.2.1"><h4 data-number="4.2.1" class="anchored" data-anchor-id="covariance-and-pearsons-correlation">
<span class="header-section-number">4.2.1</span> Covariance and Pearson’s Correlation</h4>
<p><strong>Covariance</strong> is one common way of measuring dependence between two <strong>numeric</strong> random variables. Let us check its formal definition.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition of Covariance
</div>
</div>
<div class="callout-body-container callout-body">
<p>Covariance measures how much two random variables jointly vary and in what direction. Let <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> be two random variables; their covariance is formally defined as follows:</p>
<p><span class="math display">\[\operatorname{Cov}(X, Y) = \mathbb{E}[(X-\mu_X)(Y-\mu_Y)],\]</span></p>
<p>where <span class="math inline">\(\mu_X = \mathbb{E}(X)\)</span> and <span class="math inline">\(\mu_Y = \mathbb{E}(Y)\)</span> are the respective means (or expected values) of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. After some algebraic and expected value manipulations, this equation reduces to a more practical form to work with:</p>
<p><span class="math display">\[\operatorname{Cov}(X, Y) = \mathbb{E}(XY) - \left[ \mathbb{E}(X)\mathbb{E}(Y) \right],\]</span></p>
<p>where <span class="math inline">\(\mathbb{E}(XY)\)</span> is the mean (or expected value) of the multiplication of the random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</p>
</div>
</div>
<p>For the ship example involving <span class="math inline">\(\text{LOS}\)</span> and <span class="math inline">\(\text{Gangs}\)</span>, let us recheck the corresponding <code>joint_distribution</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">joint_distribution</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Gangs = 1</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Gangs = 2</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Gangs = 3</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Gangs = 4</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 1</td>
<td style="text-align: center;">0.00170</td>
<td style="text-align: center;">0.04253</td>
<td style="text-align: center;">0.12471</td>
<td style="text-align: center;">0.08106</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 2</td>
<td style="text-align: center;">0.02664</td>
<td style="text-align: center;">0.16981</td>
<td style="text-align: center;">0.13598</td>
<td style="text-align: center;">0.01757</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 3</td>
<td style="text-align: center;">0.05109</td>
<td style="text-align: center;">0.11563</td>
<td style="text-align: center;">0.03203</td>
<td style="text-align: center;">0.00125</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 4</td>
<td style="text-align: center;">0.04653</td>
<td style="text-align: center;">0.04744</td>
<td style="text-align: center;">0.00593</td>
<td style="text-align: center;">0.00010</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">LOS = 5</td>
<td style="text-align: center;">0.07404</td>
<td style="text-align: center;">0.02459</td>
<td style="text-align: center;">0.00135</td>
<td style="text-align: center;">0.00002</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Note that, in general for a larger <span class="math inline">\(\text{LOS}\)</span>, there are larger probabilities associated with a smaller gang demand; <strong>this inverse relationship indicates negative covariance</strong>. Now, let us code the marginal PMFs of <span class="math inline">\(\text{LOS}\)</span> and <span class="math inline">\(\text{Gangs}\)</span>:</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">Marginal_PMF_LOS</span> <span class="op">&lt;-</span> <span class="fu">tribble</span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">n_days</span>, <span class="op">~</span><span class="va">p</span>,</span>
<span>  <span class="fl">1</span>, <span class="fl">0.25</span>,</span>
<span>  <span class="fl">2</span>, <span class="fl">0.35</span>,</span>
<span>  <span class="fl">3</span>, <span class="fl">0.2</span>,</span>
<span>  <span class="fl">4</span>, <span class="fl">0.1</span>,</span>
<span>  <span class="fl">5</span>, <span class="fl">0.1</span></span>
<span><span class="op">)</span></span>
<span><span class="va">Marginal_PMF_LOS</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  n_days     p
   &lt;dbl&gt; &lt;dbl&gt;
1      1  0.25
2      2  0.35
3      3  0.2 
4      4  0.1 
5      5  0.1 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">Marginal_PMF_Gangs</span> <span class="op">&lt;-</span> <span class="fu">tribble</span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">n_gangs</span>, <span class="op">~</span><span class="va">p</span>,</span>
<span>  <span class="fl">1</span>, <span class="fl">0.2</span>,</span>
<span>  <span class="fl">2</span>, <span class="fl">0.4</span>,</span>
<span>  <span class="fl">3</span>, <span class="fl">0.3</span>,</span>
<span>  <span class="fl">4</span>, <span class="fl">0.1</span>,</span>
<span><span class="op">)</span></span>
<span><span class="va">Marginal_PMF_Gangs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  n_gangs     p
    &lt;dbl&gt; &lt;dbl&gt;
1       1   0.2
2       2   0.4
3       3   0.3
4       4   0.1</code></pre>
</div>
</div>
<p>Using our <code>joint_distribution</code>, along with <code>Marginal_PMF_LOS</code> and <code>Marginal_PMF_Gangs</code>, we can calculate the covariance using the second formula. First of all, let us compute the corresponding marginal expected values:</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Expected value of LOS, E(LOS)</span></span>
<span><span class="va">E_LOS</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">Marginal_PMF_LOS</span><span class="op">$</span><span class="va">n_days</span> <span class="op">*</span> <span class="va">Marginal_PMF_LOS</span><span class="op">$</span><span class="va">p</span><span class="op">)</span></span>
<span><span class="va">E_LOS</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.45</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Expected value of Gangs, E(Gangs)</span></span>
<span><span class="va">E_Gangs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">Marginal_PMF_Gangs</span><span class="op">$</span><span class="va">n_gangs</span> <span class="op">*</span> <span class="va">Marginal_PMF_Gangs</span><span class="op">$</span><span class="va">p</span><span class="op">)</span></span>
<span><span class="va">E_Gangs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.3</code></pre>
</div>
</div>
<p>Now, we need the expected value of the multiplication of both random variables. But firstly, we need to “<em>melt</em>” our <code>joint_distribution</code> matrix as follows:</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Melting (manually!) our matrix containing the joint distribution of LOS and Gangs</span></span>
<span><span class="va">joint_distribution</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  LOS <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">4</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">4</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">4</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">4</span><span class="op">)</span><span class="op">)</span>, Gangs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">4</span>, <span class="fl">5</span><span class="op">)</span>,</span>
<span>  p <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>    <span class="fl">0.00170</span>, <span class="fl">0.04253</span>, <span class="fl">0.12471</span>, <span class="fl">0.08106</span>,</span>
<span>    <span class="fl">0.02664</span>, <span class="fl">0.16981</span>, <span class="fl">0.13598</span>, <span class="fl">0.01757</span>,</span>
<span>    <span class="fl">0.05109</span>, <span class="fl">0.11563</span>, <span class="fl">0.03203</span>, <span class="fl">0.00125</span>,</span>
<span>    <span class="fl">0.04653</span>, <span class="fl">0.04744</span>, <span class="fl">0.00593</span>, <span class="fl">0.00010</span>,</span>
<span>    <span class="fl">0.07404</span>, <span class="fl">0.02459</span>, <span class="fl">0.00135</span>, <span class="fl">0.00002</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="va">joint_distribution</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   LOS Gangs       p
1    1     1 0.00170
2    1     2 0.04253
3    1     3 0.12471
4    1     4 0.08106
5    2     1 0.02664
6    2     2 0.16981
7    2     3 0.13598
8    2     4 0.01757
9    3     1 0.05109
10   3     2 0.11563
11   3     3 0.03203
12   3     4 0.00125
13   4     1 0.04653
14   4     2 0.04744
15   4     3 0.00593
16   4     4 0.00010
17   5     1 0.07404
18   5     2 0.02459
19   5     3 0.00135
20   5     4 0.00002</code></pre>
</div>
</div>
<p>Then, we compute the corresponding <strong>crossed expected value</strong>:</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Expected value LOS times Gangs, E(LOS x Gangs)</span></span>
<span><span class="va">E_LOS_Gangs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">joint_distribution</span><span class="op">$</span><span class="va">LOS</span> <span class="op">*</span> <span class="va">joint_distribution</span><span class="op">$</span><span class="va">Gangs</span> <span class="op">*</span> <span class="va">joint_distribution</span><span class="op">$</span><span class="va">p</span><span class="op">)</span></span>
<span><span class="va">E_LOS_Gangs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.89956</code></pre>
</div>
</div>
<p>The above numeric results are plugged in the covariance formula:</p>
<p><span class="math display">\[
\begin{align*}
\operatorname{Cov}(\text{LOS}, \text{Gangs}) &amp;= \mathbb{E}(\text{LOS} \cdot \text{Gangs}) - \mathbb{E}(\text{LOS})\mathbb{E}(\text{Gangs}) \\
&amp;= 4.89956 - \left[ (2.45)(2.3) \right] \\
&amp;= -0.73544.
\end{align*}
\]</span></p>
<p>Indeed, we can see that the covariance between <span class="math inline">\(\text{LOS}\)</span> and <span class="math inline">\(\text{Gangs}\)</span> is negative.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The sign of the covariance can be interpreted as follows:</p>
<ul>
<li>
<strong>Positive covariance</strong> indicates that an increase in one variable is associated with an increase in the other variable.</li>
<li>
<strong>Negative covariance</strong> indicates that an increase in one variable is associated with a decrease in the other variable.</li>
<li>
<strong>Zero covariance</strong> indicates that there is no <strong>linear</strong> trend – but this does not necessarily mean that <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent!</li>
</ul>
</div>
</div>
<p>It turns out covariance by itself is not very interpretable, because it depends on the spread of the random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. For example, if we multiply <span class="math inline">\(X\)</span> by 10, then the covariance of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> increases by a factor of 10 as well:</p>
<p><span class="math display">\[
\begin{align*}
\operatorname{Cov}(10X,Y) &amp;= \mathbb{E}(10XY) - \mathbb{E}(10X) \mathbb{E}(Y) \\
&amp;= 10\mathbb{E}(XY) - 10\mathbb{E}(X)\mathbb{E}(Y) \\
&amp;= 10[\mathbb{E}(XY) - \mathbb{E}(X) \mathbb{E}(Y)] \\
&amp;= 10\operatorname{Cov}(X,Y).
\end{align*}
\]</span></p>
<p>The scale problem in the covariance is fixed by <strong>Pearson’s correlation</strong>. Let us formally define it.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition of Pearson’s Correlation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> be two random variables, whose respective variances are defined by the variance formula, with a covariance defined as above. Pearson’s correlation <strong>standardizes</strong> the distances according to the standard deviations <span class="math inline">\(\sigma_X\)</span> and <span class="math inline">\(\sigma_Y\)</span> of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, respectively. It is defined as (<em>note proof is skipped</em>):</p>
<p><span id="eq-pearson-coefficient"><span class="math display">\[
\begin{align*}
\rho_{XY} = \operatorname{Corr}(X, Y) &amp;= \mathbb{E} \left[
   \left(\frac{X-\mu_X}{\sigma_X}\right)
   \left(\frac{Y-\mu_Y}{\sigma_Y}\right)
\right] \\
&amp;= \frac{\operatorname{Cov}(X, Y)}{\sqrt{\operatorname{Var}(X)\operatorname{Var}(Y)}}.
\end{align*}
\tag{1}\]</span></span></p>
<p>As a result of <a href="#eq-pearson-coefficient" class="quarto-xref">Equation&nbsp;1</a>, it turns out that</p>
<p><span class="math display">\[
-1 \leq \rho_{XY} \leq 1.
\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pearson’s correlation measures the <strong>strength of linear dependence</strong>:</p>
<ul>
<li>
<span class="math inline">\(-1\)</span> means a perfect negative linear relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</li>
<li>
<span class="math inline">\(0\)</span> means no linear relationship (<strong>however, this does not mean independence!</strong>).</li>
<li>
<span class="math inline">\(1\)</span> means a perfect positive linear relationship.</li>
</ul>
<p>Pearson’s correlation is ubiquitous and is often what is meant when “correlation” is referred to.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 15
</div>
</div>
<div class="callout-body-container callout-body">
<p>Answer <strong>TRUE</strong> or <strong>FALSE</strong>:</p>
<p>Covariance can be negative, but not the variance.</p>
<p><strong>A.</strong> TRUE</p>
<p><strong>B.</strong> FALSE</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 16
</div>
</div>
<div class="callout-body-container callout-body">
<p>Answer <strong>TRUE</strong> or <strong>FALSE</strong>:</p>
<p>Without any further assumptions between random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, covariance is calculated as</p>
<p><span class="math display">\[
\operatorname{Cov}(X,Y) = \mathbb{E}(XY) - \left[ \mathbb{E}(X) \mathbb{E}(Y) \right].
\]</span></p>
<p>Computing <span class="math inline">\(\mathbb{E}(XY)\)</span> requires the joint distribution, but computing <span class="math inline">\(\mathbb{E}(X) \mathbb{E}(Y)\)</span> only requires the marginals.</p>
<p><strong>A.</strong> TRUE</p>
<p><strong>B.</strong> FALSE</p>
</div>
</div>
</section><section id="kendalls-tau_k" class="level4" data-number="4.2.2"><h4 data-number="4.2.2" class="anchored" data-anchor-id="kendalls-tau_k">
<span class="header-section-number">4.2.2</span> Kendall’s <span class="math inline">\(\tau_K\)</span>
</h4>
<p>As mentioned before, although Pearson’s correlation is ubiquitous, its forced adherence to measuring <strong>linear dependence</strong> is a big downfall, especially because many relationships between real-world variables are not linear. Hence, there is an alternative measure called Kendall’s <span class="math inline">\(\tau_K\)</span>. Its formal definition can be found below.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition of Kendall’s <span class="math inline">\(\tau_K\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Kendall’s <span class="math inline">\(\tau_K\)</span> is an alternative measure of dependence between random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. Unlike Pearson’s correlation, which measures linear dependence, Kendall’s <span class="math inline">\(\tau_K\)</span> can measure non-linear dependence.</p>
<p>That said, instead of measuring <strong>concordance</strong> between each observation <span class="math inline">\((x, y)\)</span> and the means <span class="math inline">\((\mu_x, \mu_y)\)</span>, it measures concordance between <strong>each pair</strong> of observations <span class="math inline">\((x_i, y_i)\)</span> and <span class="math inline">\((x_j, y_j)\)</span> with <span class="math inline">\(i \neq j\)</span>:</p>
<ul>
<li>
<strong>Concordant</strong>, which gets a positive sign, means <span class="math display">\[
\begin{gather*}
x_i &lt; x_j \quad \text{and} \quad y_i &lt; y_j, \\
\text{or} \\
x_i &gt; x_j \quad \text{and} \quad y_i &gt; y_j.
\end{gather*}
\]</span>
</li>
<li>
<strong>Discordant</strong>, which gets a negative sign, means <span class="math display">\[
\begin{gather*}
x_i &lt; x_j \quad \text{and} \quad y_i &gt; y_j, \\
\text{or} \\
x_i &gt; x_j \quad \text{and} \quad y_i &lt; y_j.
\end{gather*}
\]</span>
</li>
</ul>
<p>The formal definition is</p>
<p><span class="math display">\[
\tau_K = \frac{\text{Number of concordant pairs} - \text{Number of discordant pairs}}{{n \choose 2}},
\]</span></p>
<p>with the “true” Kendall’s <span class="math inline">\(\tau_K\)</span> value obtained by sending <span class="math inline">\(n \rightarrow \infty\)</span> (this is the <strong>estimation paradigm</strong> in frequentist Statistics!). Here, <span class="math inline">\(n\)</span> is the sample size (i.e., the number of data points).</p>
</div>
</div>
<p><strong>As in Pearson’s correlation</strong>, Kendall’s <span class="math inline">\(\tau_K\)</span> is between -1 and 1, and measures dependence’s strength (and direction). For instance, consider the two correlation measures for the following hypothetical dataset plotted below. Note that we are creating this dataset as follows:</p>
<p><span class="math display">\[y = x^{1/3},\]</span></p>
<p>which is a non-linear dependency between <code>x</code> and <code>y</code>. Moreover, we are creating a sequence for <code>x</code> from <code>0</code> to <code>100</code> by <code>5</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">non_linear_pairs</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span>from <span class="op">=</span> <span class="fl">0</span>, to <span class="op">=</span> <span class="fl">100</span>, by <span class="op">=</span> <span class="fl">5</span><span class="op">)</span>, y <span class="op">=</span> <span class="va">x</span><span class="op">^</span><span class="op">(</span><span class="fl">1</span> <span class="op">/</span><span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">non_linear_pairs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 2
       x     y
   &lt;dbl&gt; &lt;dbl&gt;
 1     0  0   
 2     5  1.71
 3    10  2.15
 4    15  2.47
 5    20  2.71
 6    25  2.92
 7    30  3.11
 8    35  3.27
 9    40  3.42
10    45  3.56
# ℹ 11 more rows</code></pre>
</div>
</div>
<p>The above <span class="math inline">\(n = 21\)</span> pairs from <code>non_linear_pairs</code> are plotted below. We clearly see a <strong>non-linear relationship</strong> between <code>x</code> and <code>y</code>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03_lecture-joint_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="1200"></p>
</figure>
</div>
</div>
</div>
<p>In <code>R</code>, the sample Kendall’s <span class="math inline">\(\tau_K\)</span> can be calculated using the <code><a href="https://rdrr.io/r/stats/cor.html">cor()</a></code> function with <code>method = "kendall"</code>. On the other hand, Pearson’s correlation can be computed via <code>method = "pearson"</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tribble</span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">Pearson</span>, <span class="op">~</span><span class="va">Kendall</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">non_linear_pairs</span>, method <span class="op">=</span> <span class="st">"pearson"</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">]</span>, <span class="fl">4</span><span class="op">)</span>,</span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">non_linear_pairs</span>, method <span class="op">=</span> <span class="st">"kendall"</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">]</span>, <span class="fl">4</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: center;">Pearson</th>
<th style="text-align: center;">Kendall</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: center;">0.9097</td>
<td style="text-align: center;">1</td>
</tr></tbody>
</table>
</div>
</div>
<p>Note that this dataset’s sample Pearson’s correlation is not 1! Recall it measures linear dependence, which is not true in <code>non_linear_pairs</code>. On the other hand, Kendall’s <span class="math inline">\(\tau_k\)</span> only measures the strength of <strong>monotonic dependence</strong>; thus, it equals 1.</p>
<p>Now, let us check a different case that does not fit the conditions for Pearson’s correlation and Kendall’s <span class="math inline">\(\tau_K\)</span>.</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">parabola_pairs</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span>from <span class="op">=</span> <span class="op">-</span><span class="fl">50</span>, to <span class="op">=</span> <span class="fl">50</span>, by <span class="op">=</span> <span class="fl">5</span><span class="op">)</span>, y <span class="op">=</span> <span class="va">x</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span></span>
<span><span class="va">parabola_pairs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 2
       x     y
   &lt;dbl&gt; &lt;dbl&gt;
 1   -50  2500
 2   -45  2025
 3   -40  1600
 4   -35  1225
 5   -30   900
 6   -25   625
 7   -20   400
 8   -15   225
 9   -10   100
10    -5    25
# ℹ 11 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="03_lecture-joint_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="1200"></p>
</figure>
</div>
</div>
</div>
<p>Patterns like the above parabola are not monotonically increasing or decreasing (i.e., there is no monotonic dependence!). Hence, this matter will not even be captured by Kendall’s <span class="math inline">\(\tau_K\)</span> either:</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tribble</span><span class="op">(</span></span>
<span>    <span class="op">~</span> <span class="va">Pearson</span>, <span class="op">~</span> <span class="va">Kendall</span>,</span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">parabola_pairs</span>, method <span class="op">=</span> <span class="st">"pearson"</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">]</span>, <span class="fl">4</span><span class="op">)</span>, </span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">parabola_pairs</span>, method <span class="op">=</span> <span class="st">"kendall"</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">]</span>, <span class="fl">4</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: center;">Pearson</th>
<th style="text-align: center;">Kendall</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr></tbody>
</table>
</div>
</div>
<p>Even though both dependence measures (Pearson and Kendall) are 0, there is actually deterministic dependence here (i.e., <span class="math inline">\(X\)</span> <strong>determines</strong> <span class="math inline">\(Y\)</span>). Luckily, there are many monotonic relationships in practice, making Kendall’s <span class="math inline">\(\tau_K\)</span> a handy measure of dependence.</p>
</section><section id="optional-mutual-information" class="level4" data-number="4.2.3"><h4 data-number="4.2.3" class="anchored" data-anchor-id="optional-mutual-information">
<span class="header-section-number">4.2.3</span> (Optional) Mutual Information</h4>
<p>Covariance and correlation measure the strength of dependence for numeric random variables, but what about categorical random variables? Back in the first lecture, we saw entropy as a measure of spread that works even for categorical variables. If covariance is a (multivariate) generalization of variance, do we have a (multivariate) generalization of entropy? The answer is yes! And it is called <strong>mutual information</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition of Mutual Information
</div>
</div>
<div class="callout-body-container callout-body">
<p>The mutual information between two random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is defined as</p>
<p><span class="math display">\[
H(X,Y) = \displaystyle \sum_x \displaystyle \sum_y P(X = x \cap Y = y)\log\left[\frac{P(X = x \cap Y = y)}{P(X = x) \cdot P(Y = y)}\right].
\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Later, you will also encounter <strong>cross-entropy</strong>, which is somewhat related to mutual information, except that it is not symmetric between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>; that is <span class="math inline">\(H(X , Y) \neq H(Y,X)\)</span>. Again, when you get to your Machine Learning courses, the motivation for this will make more sense.</p>
</div>
</div>
</section></section><section id="variance-of-a-sum-involving-two-non-independent-random-variables" class="level3" data-number="4.3"><h3 data-number="4.3" class="anchored" data-anchor-id="variance-of-a-sum-involving-two-non-independent-random-variables">
<span class="header-section-number">4.3</span> Variance of a Sum Involving Two Non-Independent Random Variables</h3>
<p>Suppose <strong><span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are not independent random variables</strong>. Therefore, the variance of their sum is:</p>
<p><span class="math display">\[
\operatorname{Var}(X + Y) = \operatorname{Var}(X) + \operatorname{Var}(Y) + 2\operatorname{Cov}(X, Y).
\]</span></p>
<p>Furthermore, <strong>if <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent</strong>, then</p>
<p><span class="math display">\[
\mathbb{E}(XY) = \mathbb{E}(X) \mathbb{E}(Y).
\]</span></p>
<p>Using the above equation, the covariance is</p>
<p><span class="math display">\[
\begin{align*}
\operatorname{Cov}(X, Y) &amp;= \mathbb{E}(XY) - \left[ \mathbb{E}(X)\mathbb{E}(Y) \right] \\
&amp;= \left[ \mathbb{E}(X) \mathbb{E}(Y) \right] - \left[ \mathbb{E}(X)\mathbb{E}(Y) \right] \\
&amp;= 0,
\end{align*}
\]</span></p>
<p>and the sum becomes:</p>
<p><span class="math display">\[
\operatorname{Var}(X + Y) = \operatorname{Var}(X) + \operatorname{Var}(Y).
\]</span></p>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ubc-mds\.github\.io\/DSCI_551_stat-prob-dsci\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
          // default icon
          link.classList.add("external");
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../notes/02_lecture-parametric-families.html" class="pagination-link" aria-label="Lecture 2: Parametric Families">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Lecture 2: Parametric Families</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../notes/04_lecture-conditional.html" class="pagination-link" aria-label="Lecture 4: Conditional Probabilities">
        <span class="nav-page-text">Lecture 4: Conditional Probabilities</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/UBC-MDS/DSCI_551_stat-prob-dsci/issues" class="toc-action"><i class="bi bi-chat-right"></i>Report an issue</a></li></ul></div></div></div></footer><script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>