<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.53">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Lecture 4: Conditional Probabilities – DSCI 551: Descriptive Statistics and Probability for Data Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notes/05_lecture-continuous.html" rel="next">
<link href="../notes/03_lecture-joint.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><style>html{ scroll-behavior: smooth; }</style>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script><link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script><link rel="stylesheet" href="../styles.css">
</head>
<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">DSCI 551: Descriptive Statistics and Probability for Data Science</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
<ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item compact">
    <a class="nav-link" href="https://github.com/UBC-MDS/DSCI_551_stat-prob-dsci"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../learning-goals.html">Lectures</a></li><li class="breadcrumb-item"><a href="../notes/04_lecture-conditional.html">Lecture 4: Conditional Probabilities</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../notes/img/UBC_MDS_logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none"></a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Lectures</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../learning-goals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learning Goals by Lecture</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/01_lecture-uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 1: Depicting Uncertainty</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/02_lecture-parametric-families.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 2: Parametric Families</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/03_lecture-joint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 3: Joint Probability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/04_lecture-conditional.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Lecture 4: Conditional Probabilities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/05_lecture-continuous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 5: Continuous Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/06_lecture-continuous-families.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 6: Common Distribution Families and Conditioning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/07_lecture-maximum-likelihood-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 7: Maximum Likelihood Estimation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/08_lecture-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lecture 8: Simulation</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/appendix-prob-cheatsheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Probability Cheatsheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/appendix-dist-cheatsheet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Distribution Cheatsheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/appendix-greek-alphabet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Greek Alphabet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../LICENSE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">License</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="4"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#slides" id="toc-slides" class="nav-link active" data-scroll-target="#slides"><span class="header-section-number">1</span> Slides</a></li>
  <li><a href="#learning-goals" id="toc-learning-goals" class="nav-link" data-scroll-target="#learning-goals"><span class="header-section-number">2</span> Learning Goals</a></li>
  <li>
<a href="#sec-discrete-univariate-conditional-distributions" id="toc-sec-discrete-univariate-conditional-distributions" class="nav-link" data-scroll-target="#sec-discrete-univariate-conditional-distributions"><span class="header-section-number">3</span> Univariate Conditional Distributions</a>
  <ul>
<li><a href="#table-approach" id="toc-table-approach" class="nav-link" data-scroll-target="#table-approach"><span class="header-section-number">3.1</span> Table Approach</a></li>
  <li><a href="#formula-approach" id="toc-formula-approach" class="nav-link" data-scroll-target="#formula-approach"><span class="header-section-number">3.2</span> Formula Approach</a></li>
  </ul>
</li>
  <li>
<a href="#sec-discrete-multivariate-conditional-distributions" id="toc-sec-discrete-multivariate-conditional-distributions" class="nav-link" data-scroll-target="#sec-discrete-multivariate-conditional-distributions"><span class="header-section-number">4</span> Multivariate Conditional Distributions</a>
  <ul>
<li><a href="#table-approach-1" id="toc-table-approach-1" class="nav-link" data-scroll-target="#table-approach-1"><span class="header-section-number">4.1</span> Table Approach</a></li>
  <li><a href="#formula-approach-1" id="toc-formula-approach-1" class="nav-link" data-scroll-target="#formula-approach-1"><span class="header-section-number">4.2</span> Formula Approach</a></li>
  <li><a href="#independence-and-conditional-probabilities" id="toc-independence-and-conditional-probabilities" class="nav-link" data-scroll-target="#independence-and-conditional-probabilities"><span class="header-section-number">4.3</span> Independence and Conditional Probabilities</a></li>
  <li><a href="#law-of-total-probabilityexpectation" id="toc-law-of-total-probabilityexpectation" class="nav-link" data-scroll-target="#law-of-total-probabilityexpectation"><span class="header-section-number">4.4</span> Law of Total Probability/Expectation</a></li>
  </ul>
</li>
  <li><a href="#conditional-independence" id="toc-conditional-independence" class="nav-link" data-scroll-target="#conditional-independence"><span class="header-section-number">5</span> Conditional Independence</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/UBC-MDS/DSCI_551_stat-prob-dsci/issues" class="toc-action"><i class="bi bi-chat-right"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../learning-goals.html">Lectures</a></li><li class="breadcrumb-item"><a href="../notes/04_lecture-conditional.html">Lecture 4: Conditional Probabilities</a></li></ol></nav><div class="quarto-title">
<h1 class="title">Lecture 4: Conditional Probabilities</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="slides" class="level2" data-number="1"><h2 data-number="1" class="anchored" data-anchor-id="slides">
<span class="header-section-number">1</span> Slides</h2>
<iframe src="../slides/04_lecture-conditional/04_lecture-conditional.html" width="100%" height="600px" style="border: none;">
</iframe>
</section><section id="learning-goals" class="level2" data-number="2"><h2 data-number="2" class="anchored" data-anchor-id="learning-goals">
<span class="header-section-number">2</span> Learning Goals</h2>
<p>By the end of this lecture, you should be able to:</p>
<ul>
<li>Calculate conditional distributions when given a full distribution.</li>
<li>Obtain the marginal mean from conditional means and marginal probabilities, using the Law of Total Expectation.</li>
<li>Use the Law of Total Probability to convert between conditional, marginal distributions, and joint distributions.</li>
<li>Compare and contrast independence versus conditional independence.</li>
</ul></section><section id="sec-discrete-univariate-conditional-distributions" class="level2" data-number="3"><h2 data-number="3" class="anchored" data-anchor-id="sec-discrete-univariate-conditional-distributions">
<span class="header-section-number">3</span> Univariate Conditional Distributions</h2>
<p>Let us start with the following inquiry:</p>
<blockquote class="blockquote">
<p>Probability distributions describe an uncertain outcome, but what if we have partial information?</p>
</blockquote>
<div id="fig-cargo-ship-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-cargo-ship-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/ship.png" class="img-fluid figure-img" width="650">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cargo-ship-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: A cargo ship.
</figcaption></figure>
</div>
<p>Consider the example of ships arriving at the port of Vancouver again. Each ship will stay at port for a random number of days, which we will call the <strong>length of stay</strong> (<span class="math inline">\(\text{LOS}\)</span>). For the sake of our notation, let us call it <span class="math inline">\(L\)</span>, which has the probability mass function (PMF) from <a href="#tbl-pmf-LOS" class="quarto-xref">Table&nbsp;13</a>.</p>
<div class="cell">
<div id="tbl-pmf-LOS" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pmf-LOS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Probability mass function for the lenght of stay in days.
</figcaption><div aria-describedby="tbl-pmf-LOS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">L (Days)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Probability</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.35</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.20</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">0.10</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>We can also plot this PMF as a bar chart in <a href="#fig-pmf-LOS" class="quarto-xref">Figure&nbsp;2</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-pmf-LOS" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-pmf-LOS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_lecture-conditional_files/figure-html/fig-pmf-LOS-1.png" class="img-fluid figure-img" width="1200">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pmf-LOS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Probability mass function for the lenght of stay in days.
</figcaption></figure>
</div>
</div>
</div>
<p>Before continuing with our example, let us formally define conditional probability.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition of Conditional Probability
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> be two events of interest within the sample <span class="math inline">\(S\)</span>, and <span class="math inline">\(P(B) &gt; 0\)</span>, then the <strong>conditional probability</strong> of <span class="math inline">\(A\)</span> given <span class="math inline">\(B\)</span> is defined as:</p>
<p><span id="eq-conditional-probability"><span class="math display">\[P(A \mid B) = \frac{P(A \cap B)}{P(B)} \tag{1}\]</span></span></p>
<p>What is going on in <a href="#eq-conditional-probability" class="quarto-xref">Equation&nbsp;1</a>? Basically, event <span class="math inline">\(B\)</span> is becoming the new sample space; note that <span class="math inline">\(P(B \mid B) = 1\)</span>. The tweak here is that our original sample space <span class="math inline">\(S\)</span> has been updated to <span class="math inline">\(B\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition of Conditional Probability Distribution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> be two events of interest within the sample <span class="math inline">\(S\)</span>. A conditional probability distribution of event <span class="math inline">\(A\)</span> given <span class="math inline">\(B\)</span> is a <strong>proper probability distribution</strong> for event <span class="math inline">\(A\)</span> after observing event <span class="math inline">\(B\)</span>. This distribution is restricted to the subsample space provided by event <span class="math inline">\(B\)</span>.</p>
</div>
</div>
<p>Now, suppose a ship has been at port for 2 days now, and it will be staying longer. <strong>This means that we know the <span class="math inline">\(L\)</span> will be greater than 2.</strong> Now we might wonder, what is the distribution of the <span class="math inline">\(L\)</span> now? Using symbols, this is written as</p>
<p><span class="math display">\[P(L = l \mid L &gt; 2),\]</span></p>
<p>where the bar “<span class="math inline">\(\mid\)</span>” reads as “given” or “conditional on” the event <span class="math inline">\(L &gt; 2\)</span>. One of these probabilities, like <span class="math inline">\(P(L = 3 \mid L &gt; 2)\)</span>, is called a <strong>conditional probability</strong>, and the whole distribution, <span class="math inline">\(P(L = l \mid L &gt; 2)\)</span> for all <span class="math inline">\(l\)</span>, is called a <strong>conditional probability distribution</strong>.</p>
<p>It is essential to stop here for a moment and recognize that this is, in fact, a probability distribution, i.e.,</p>
<p><span id="eq-ships-conditional"><span class="math display">\[\sum_{l = 3}^5 P(L = l \mid L &gt; 2) = 1 \tag{2}\]</span></span></p>
<p>Why is this? Well, the ship has been here for two days, and something still has to happen. So just like <span class="math inline">\(P(L = l)\)</span> was a probability distribution with probabilities summing to 1, <span class="math inline">\(P(L = l \mid L &gt; 2)\)</span> is also a probability distribution with probabilities summing to 1. <strong>But the probabilities will be different because they have to be updated given the information that <span class="math inline">\(L &gt; 2\)</span>.</strong></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note that, in <a href="#eq-ships-conditional" class="quarto-xref">Equation&nbsp;2</a>, we restrict the values of <span class="math inline">\(l\)</span> from <span class="math inline">\(3\)</span> to <span class="math inline">\(5\)</span> given the condition <span class="math inline">\(L &gt; 2\)</span>.</p>
</div>
</div>
<p><strong>In the case of a discrete random variable</strong>, we can calculate a conditional distribution in two ways:</p>
<ol type="1">
<li>A <strong>table approach</strong> and</li>
<li>a <strong>formula approach</strong>.</li>
</ol>
<section id="table-approach" class="level3" data-number="3.1"><h3 data-number="3.1" class="anchored" data-anchor-id="table-approach">
<span class="header-section-number">3.1</span> Table Approach</h3>
<p>Let us start with the table approach for our cargo ship example via the following steps:</p>
<ol type="1">
<li>Subset the PMF table to only those outcomes that satisfy the <strong>condition</strong> (<span class="math inline">\(L &gt; 2\)</span> in this case). You will end up with a sub-table.</li>
<li>Re-normalize the remaining probabilities so that they add up to 1. You will end up with the conditional distribution under that condition.</li>
</ol>
<p>Recall our original PMF as shown in <a href="#tbl-pmf-LOS-2" class="quarto-xref">Table&nbsp;2</a>.</p>
<div class="cell">
<div id="tbl-pmf-LOS-2" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pmf-LOS-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Probability mass function for the lenght of stay in days.
</figcaption><div aria-describedby="tbl-pmf-LOS-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">L (Days)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Probability</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.35</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.20</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">0.10</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Nevertheless, now that we know <span class="math inline">\(L &gt; 2\)</span>, we have to “delete” some of these options (see <a href="#tbl-step-1-conditional-pmf-L" class="quarto-xref">Table&nbsp;3</a>).</p>
<div id="tbl-step-1-conditional-pmf-L" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-step-1-conditional-pmf-L-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: First step to update of the probability mass function (PMF) of random variable <span class="math inline">\(L\)</span> given condition <span class="math inline">\(L &gt; 2\)</span>.
</figcaption><div aria-describedby="tbl-step-1-conditional-pmf-L-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;">
<span class="math inline">\(L\)</span> (Days)</th>
<th style="text-align: center;"><span class="math inline">\(P(L = l \mid L &gt; 2)\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">IMPOSSIBLE</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">IMPOSSIBLE</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">Used to be 0.20</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">Used to be 0.10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">Used to be 0.10</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Since the only possible outcomes now are <span class="math inline">\(L = 3, 4, 5\)</span>, we <strong>scale</strong> (or <strong>re-normalize</strong>) these remaining probabilities up to bigger values so that they all add up to 1 again. In this case,</p>
<p><span class="math display">\[0.20 + 0.10 + 0.10 = 0.40,\]</span></p>
<p>so if we divide all the probabilities by <span class="math inline">\(0.40\)</span> in <a href="#tbl-step-1-conditional-pmf-L" class="quarto-xref">Table&nbsp;3</a>, except for <span class="math inline">\(L = 1, 2\)</span> whose probabilities are now 0, we will be good to go (see <a href="#tbl-conditional-pmf-L-2" class="quarto-xref">Table&nbsp;4</a>).</p>
<div id="tbl-conditional-pmf-L-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-conditional-pmf-L-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Conditional probability mass function (PMF) of random variable <span class="math inline">\(L\)</span> given condition <span class="math inline">\(L &gt; 2\)</span>.
</figcaption><div aria-describedby="tbl-conditional-pmf-L-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;">
<span class="math inline">\(L\)</span> (Days)</th>
<th style="text-align: center;"><span class="math inline">\(P(L = l \mid L &gt; 2)\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.50</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">0.25</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Note how, for outcomes satisfying the condition <span class="math inline">\(L &gt; 2\)</span>, the <strong>ratios</strong> of the probabilities stay the same: <span class="math inline">\(L = 3\)</span> used to be twice as probable as <span class="math inline">\(L = 4\)</span> for instance, and that is still the case after conditioning.</p>
</section><section id="formula-approach" class="level3" data-number="3.2"><h3 data-number="3.2" class="anchored" data-anchor-id="formula-approach">
<span class="header-section-number">3.2</span> Formula Approach</h3>
<p>Now, let us proceed with the formula approach via <a href="#eq-conditional-probability" class="quarto-xref">Equation&nbsp;1</a>. For our example, the event <span class="math inline">\(A\)</span> is <span class="math inline">\(L = l\)</span> and the event <span class="math inline">\(B\)</span> is <span class="math inline">\(L &gt; 2\)</span>. Plugging this in, we get</p>
<p><span class="math display">\[P(L = l \mid L &gt; 2) = \frac{P(L = l \cap L &gt; 2)}{P(L &gt; 2)} = \frac{P(L = l)}{P(L &gt; 2)} \quad \text{for} \quad l = 3, 4, 5.\]</span></p>
<p>The only real “trick” is the numerator. How did we reduce the convoluted event</p>
<p><span class="math display">\[L = l \cap L &gt; 2\]</span></p>
<p>to the simple event <span class="math inline">\(L = l\)</span> for <span class="math inline">\(l = 3, 4, 5\)</span>? The “trick” is to go through all outcomes and check which ones satisfy the requirement</p>
<p><span class="math display">\[L = l \cap L &gt; 2.\]</span></p>
<p>This reduces to <span class="math inline">\(L = l\)</span>, as long as <span class="math inline">\(l = 3, 4, 5\)</span>.</p>
<p>Looking at the cargo ship example via the formula, we can see that the math is telling us to do the “re-normalizing” we did above: for all cases satisfying the condition, we would divide by</p>
<p><span class="math display">\[
\begin{align}
P(L &gt; 2) &amp;= P(L = 3) + P(L = 4) + P(L = 5) \\
&amp;= 0.20 + 0.10 + 0.10 \\
&amp;= 0.40.
\end{align}
\]</span></p>
<p>which is exactly what we did when we re-normalized. Thus:</p>
<p><span class="math display">\[
\begin{align}
P(L = 3 \mid L &gt; 2) &amp;= \frac{P(L = 3 \cap L &gt; 2)}{P(L &gt; 2)} \\
&amp;= \frac{P(L = 3)}{P(L &gt; 2)} \\
&amp;= \frac{0.20}{0.40} \\
&amp;= 0.50.
\end{align}
\]</span></p>
<p><span class="math display">\[
\begin{align}
P(L = 4 \mid L &gt; 2) &amp;= \frac{P(L = 4 \cap L &gt; 2)}{P(L &gt; 2)} \\
&amp;= \frac{P(L = 4)}{P(L &gt; 2)} \\
&amp;= \frac{0.10}{0.40} \\
&amp;= 0.25.
\end{align}
\]</span></p>
<p><span class="math display">\[
\begin{align}
P(L = 5 \mid L &gt; 2) &amp;= \frac{P(L = 5 \cap L &gt; 2)}{P(L &gt; 2)} \\
&amp;= \frac{P(L = 5)}{P(L &gt; 2)} \\
&amp;= \frac{0.10}{0.40} \\
&amp;= 0.25.
\end{align}
\]</span></p>
<p>So, the two approaches are equivalent, but the first one is easier to remember and a lot more intuitive.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Even though the table approach is more intuitive, it is necessary to get familiar with the conditional probability as a formula depicted in <a href="#eq-conditional-probability" class="quarto-xref">Equation&nbsp;1</a> for the Bayesian course <em>DSCI 553</em>.</p>
</div>
</div>
</section></section><section id="sec-discrete-multivariate-conditional-distributions" class="level2" data-number="4"><h2 data-number="4" class="anchored" data-anchor-id="sec-discrete-multivariate-conditional-distributions">
<span class="header-section-number">4</span> Multivariate Conditional Distributions</h2>
<p>So far, we have considered conditioning in the one-variable (i.e., univariate) case. In our cargo ship examples, if we look at</p>
<p><span class="math display">\[P(L = l \mid L &gt; 2),\]</span></p>
<p>we encounter the same random variable <span class="math inline">\(L\)</span> on both sides of the vertical bar <span class="math inline">\(\mid\)</span> in the above expression. This is often useful. However, it is more useful to think about the distribution of one random variable <strong>when conditioned on a different random variable</strong>.</p>
<p>To dig into that case, let us revisit our 2-variable example where we looked at both the <span class="math inline">\(\text{LOS}\)</span> (i.e., random variable <span class="math inline">\(L\)</span>) and the number of <span class="math inline">\(\text{Gangs}\)</span> required (i.e., random variable <span class="math inline">\(G\)</span>) via our joint distribution:</p>
<div class="cell">
<div id="tbl-joint-pmf-gangs-los" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-joint-pmf-gangs-los-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Joint probability mass function (PMF) for the number of Gangs (G) and length of stay (L) in days.
</figcaption><div aria-describedby="tbl-joint-pmf-gangs-los-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 1</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 2</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 3</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 4</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 1</td>
<td style="text-align: center;">0.0017</td>
<td style="text-align: center;">0.0425</td>
<td style="text-align: center;">0.1247</td>
<td style="text-align: center;">0.0811</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 2</td>
<td style="text-align: center;">0.0266</td>
<td style="text-align: center;">0.1698</td>
<td style="text-align: center;">0.1360</td>
<td style="text-align: center;">0.0176</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 3</td>
<td style="text-align: center;">0.0511</td>
<td style="text-align: center;">0.1156</td>
<td style="text-align: center;">0.0320</td>
<td style="text-align: center;">0.0013</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 4</td>
<td style="text-align: center;">0.0465</td>
<td style="text-align: center;">0.0474</td>
<td style="text-align: center;">0.0059</td>
<td style="text-align: center;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 5</td>
<td style="text-align: center;">0.0740</td>
<td style="text-align: center;">0.0246</td>
<td style="text-align: center;">0.0014</td>
<td style="text-align: center;">0.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Thus, suppose a ship is arriving, and they have told you they will only be staying for <strong>exactly</strong> 1 day. What is the distribution of <span class="math inline">\(G\)</span> under this information? That is, what is <span class="math inline">\(P(G = g \mid L = 1)\)</span> for all possible <span class="math inline">\(g\)</span>? We will check out the table and formula approaches once again.</p>
<section id="table-approach-1" class="level3" data-number="4.1"><h3 data-number="4.1" class="anchored" data-anchor-id="table-approach-1">
<span class="header-section-number">4.1</span> Table Approach</h3>
<p>Let us start with the table approach:</p>
<ol type="1">
<li>We are supposed to throw away all the cases where the condition is not satisfied. Isolating the outcomes satisfying the condition (<span class="math inline">\(L = 1\)</span>) in the joint distribution, we obtain the first row:</li>
</ol>
<div class="cell">
<div id="tbl-cond-pmf-gangs-los-step-1" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cond-pmf-gangs-los-step-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: First step to update of the probability mass function (PMF) of random variable G given condition L = 1.
</figcaption><div aria-describedby="tbl-cond-pmf-gangs-los-step-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 1</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 2</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 3</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 4</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 1</td>
<td style="text-align: center;">Used to be 0.0017</td>
<td style="text-align: center;">Used to be 0.0425</td>
<td style="text-align: center;">Used to be 0.1247</td>
<td style="text-align: center;">Used to be 0.0811</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 2</td>
<td style="text-align: center;">IMPOSSIBLE</td>
<td style="text-align: center;">IMPOSSIBLE</td>
<td style="text-align: center;">IMPOSSIBLE</td>
<td style="text-align: center;">IMPOSSIBLE</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 3</td>
<td style="text-align: center;">IMPOSSIBLE</td>
<td style="text-align: center;">IMPOSSIBLE</td>
<td style="text-align: center;">IMPOSSIBLE</td>
<td style="text-align: center;">IMPOSSIBLE</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 4</td>
<td style="text-align: center;">IMPOSSIBLE</td>
<td style="text-align: center;">IMPOSSIBLE</td>
<td style="text-align: center;">IMPOSSIBLE</td>
<td style="text-align: center;">IMPOSSIBLE</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 5</td>
<td style="text-align: center;">IMPOSSIBLE</td>
<td style="text-align: center;">IMPOSSIBLE</td>
<td style="text-align: center;">IMPOSSIBLE</td>
<td style="text-align: center;">IMPOSSIBLE</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ol start="2" type="1">
<li>Now, re-normalize the probabilities so that they add up to 1, by dividing them by their sum, which is</li>
</ol>
<p><span class="math display">\[0.0017 + 0.0425 + 0.1247 + 0.0811 = 0.25.\]</span></p>
<div class="cell">
<div id="tbl-cond-pmf-gangs-los-step-2" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cond-pmf-gangs-los-step-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Conditional probability mass function (PMF) of random variable G given condition L = 1.
</figcaption><div aria-describedby="tbl-cond-pmf-gangs-los-step-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 1</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 2</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 3</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 4</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 1</td>
<td style="text-align: center;">0.0068</td>
<td style="text-align: center;">0.17</td>
<td style="text-align: center;">0.4988</td>
<td style="text-align: center;">0.3244</td>
</tr></tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>And this is it, we have <span class="math inline">\(P(G = g \mid L = 1)\)</span>. By the way, compare this with <strong>the marginal distribution of the number of <span class="math inline">\(\text{Gangs}\)</span></strong>:</p>
<div class="cell">
<div id="tbl-marginal-pmf-gangs" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-marginal-pmf-gangs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Marginal probability mass function (PMF) of random variable G.
</figcaption><div aria-describedby="tbl-marginal-pmf-gangs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">G = 1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">G = 2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">G = 3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">G = 4</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">0.1</td>
</tr></tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Or, preferably, here is the same comparison in plot format:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-pmfs-gangs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-pmfs-gangs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_lecture-conditional_files/figure-html/fig-pmfs-gangs-1.png" class="img-fluid figure-img" width="1200">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pmfs-gangs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Conditional and marginal probability mass functions for random variable G.
</figcaption></figure>
</div>
</div>
</div>
<p>In <a href="#fig-pmfs-gangs" class="quarto-xref">Figure&nbsp;3</a>, we see the effect of conditioning on the <span class="math inline">\(\text{LOS}\)</span> being 1 day (i.e., <span class="math inline">\(L = 1\)</span>) on the left-hand side panel. If the <span class="math inline">\(\text{LOS}\)</span> is short, we shift the PMF towards higher numbers of <span class="math inline">\(\text{Gangs}.\)</span> This would be good to know in a real shipping context! Furthermore, this result is consistent with our previous knowledge that <span class="math inline">\(\text{LOS}\)</span> and <span class="math inline">\(\text{Gangs}\)</span> are negatively correlated; a smaller <span class="math inline">\(\text{LOS}\)</span> is associated with a larger number of <span class="math inline">\(\text{Gangs}\)</span>.</p>
<p>We can also look at expected values. Firstly, <strong>let us use the respective marginal PMF for <span class="math inline">\(G\)</span> in <a href="#tbl-marginal-pmf-gangs-2" class="quarto-xref">Table&nbsp;9</a>:</strong></p>
<div class="cell">
<div id="tbl-marginal-pmf-gangs-2" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-marginal-pmf-gangs-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Marginal probability mass function (PMF) of random variable G.
</figcaption><div aria-describedby="tbl-marginal-pmf-gangs-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Probability</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">G = 1</td>
<td style="text-align: center;">0.1999</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">G = 2</td>
<td style="text-align: center;">0.3999</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">G = 3</td>
<td style="text-align: center;">0.3000</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">G = 4</td>
<td style="text-align: center;">0.1001</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Then, we can obtain the marginal expected number of <span class="math inline">\(\text{Gangs}\)</span>:</p>
<p><span class="math display">\[\begin{align}
\mathbb{E}(G) &amp;= 1(0.2) + 2(0.4) + 3(0.3) + 4(0.1) \\
&amp;= 2.3.
\end{align}\]</span></p>
<p>That said, after conditioning on <span class="math inline">\(L = 1\)</span>, we can obtain the <strong>conditional expectation</strong> of the number of <span class="math inline">\(\text{Gangs}\)</span>. This is exactly the same formula for expected value, but this time using the conditional distribution for <span class="math inline">\(\text{Gangs}\)</span> given <span class="math inline">\(L = 1\)</span> asin <a href="#tbl-cond-pmf-gangs-los-step-2-2" class="quarto-xref">Table&nbsp;10</a>.</p>
<div class="cell">
<div id="tbl-cond-pmf-gangs-los-step-2-2" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cond-pmf-gangs-los-step-2-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Conditional probability mass function (PMF) of random variable G given condition L = 1.
</figcaption><div aria-describedby="tbl-cond-pmf-gangs-los-step-2-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 1</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 2</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 3</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 4</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 1</td>
<td style="text-align: center;">0.0068</td>
<td style="text-align: center;">0.17</td>
<td style="text-align: center;">0.4988</td>
<td style="text-align: center;">0.3244</td>
</tr></tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>We write it as <span class="math inline">\(\mathbb{E}(G \mid L = 1)\)</span>. It is computed as follows:</p>
<p><span class="math display">\[\begin{align}
\mathbb{E}(G \mid L = 1) &amp;= 1(0.0068) + 2(0.17) + 3(0.4988) + 4(0.3244) \\
&amp;= 3.1408.
\end{align}\]</span></p>
<p>We see that indeed the expected number of <span class="math inline">\(\text{Gangs}\)</span> increased once we conditioned on the <span class="math inline">\(\text{LOS}\)</span> being only 1 day.</p>
</section><section id="formula-approach-1" class="level3" data-number="4.2"><h3 data-number="4.2" class="anchored" data-anchor-id="formula-approach-1">
<span class="header-section-number">4.2</span> Formula Approach</h3>
<p>Now, let us proceed with the formula approach. By applying the formula for conditional probabilities <a href="#eq-conditional-probability" class="quarto-xref">Equation&nbsp;1</a>, we get</p>
<p><span id="eq-ship-formula-approach"><span class="math display">\[P(G = g \mid L = 1) = \frac{P(G = g \cap L = 1)}{P(L = 1)} \quad \text{for} \quad g = 1, 2, 3, 4. \tag{3}\]</span></span></p>
<p>Let us check the joint distribution in <a href="#tbl-joint-pmf-gangs-los-2" class="quarto-xref">Table&nbsp;11</a>.</p>
<div class="cell">
<div id="tbl-joint-pmf-gangs-los-2" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-joint-pmf-gangs-los-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: Joint probability mass function (PMF) for the number of Gangs (G) and length of stay (L) in days.
</figcaption><div aria-describedby="tbl-joint-pmf-gangs-los-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 1</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 2</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 3</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 4</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 1</td>
<td style="text-align: center;">0.0017</td>
<td style="text-align: center;">0.0425</td>
<td style="text-align: center;">0.1247</td>
<td style="text-align: center;">0.0811</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 2</td>
<td style="text-align: center;">0.0266</td>
<td style="text-align: center;">0.1698</td>
<td style="text-align: center;">0.1360</td>
<td style="text-align: center;">0.0176</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 3</td>
<td style="text-align: center;">0.0511</td>
<td style="text-align: center;">0.1156</td>
<td style="text-align: center;">0.0320</td>
<td style="text-align: center;">0.0013</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 4</td>
<td style="text-align: center;">0.0465</td>
<td style="text-align: center;">0.0474</td>
<td style="text-align: center;">0.0059</td>
<td style="text-align: center;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 5</td>
<td style="text-align: center;">0.0740</td>
<td style="text-align: center;">0.0246</td>
<td style="text-align: center;">0.0014</td>
<td style="text-align: center;">0.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Then, we can obtain the denominator from <a href="#eq-ship-formula-approach" class="quarto-xref">Equation&nbsp;3</a> as follows:</p>
<p><span class="math display">\[\begin{align}
P(L = 1) &amp;= P(G = 1 \cap L = 1) + P(G = 2 \cap L = 1) + \\
&amp; \qquad P(G = 3 \cap L = 1) + P(G = 4 \cap L = 1) \\
&amp;= 0.0017 + 0.0425 + 0.1247 +  0.0811 \\
&amp;= 0.25.
\end{align}\]</span></p>
<p>Finally, using the first row of the joint distribution to obtain the intersections from the numerator, we compute the conditional probabilities:</p>
<p><span class="math display">\[\begin{align}
P(G = 1 \mid L = 1) &amp;= \frac{P(G = 1 \cap L = 1)}{P(L = 1)} \\
&amp;= \frac{0.0017}{0.25} \\
&amp;= 0.0068.
\end{align}\]</span></p>
<p><span class="math display">\[\begin{align}
P(G = 2 \mid L = 1) &amp;= \frac{P(G = 2 \cap L = 1)}{P(L = 1)} \\
&amp;= \frac{0.0425}{0.25} \\
&amp;= 0.1701.
\end{align}\]</span></p>
<p><span class="math display">\[\begin{align}
P(G = 3 \mid L = 1) &amp;= \frac{P(G = 3 \cap L = 1)}{P(L = 1)} \\
&amp;= \frac{0.1247}{0.25} \\
&amp;= 0.4988.
\end{align}\]</span></p>
<p><span class="math display">\[\begin{align}
P(G = 4 \mid L = 1) &amp;= \frac{P(G = 4 \cap L = 1)}{P(L = 1)} \\
&amp;= \frac{0.0811}{0.25} \\
&amp;= 0.3242.
\end{align}\]</span></p>
<p>And the above four conditional probabilities are part of a proper conditional PMF:</p>
<p><span class="math display">\[\begin{align}
\sum_{g = 1}^4 P(G = g \mid L = 1) &amp;= 0.0068 + 0.1701 + 0.4988 + 0.3242 \\
&amp;= 1.
\end{align}\]</span></p>
<p>Again, the table approach and the formula approach are equivalent.</p>
</section><section id="independence-and-conditional-probabilities" class="level3" data-number="4.3"><h3 data-number="4.3" class="anchored" data-anchor-id="independence-and-conditional-probabilities">
<span class="header-section-number">4.3</span> Independence and Conditional Probabilities</h3>
<p>In the previous lecture, we saw the notion of <strong>independence</strong> of random variables. We said that random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent if and only if</p>
<p><span class="math display">\[P(Y = y \cap X = x) = P(Y = y) \cdot P(X = x), \text{ for all } x \text{ and } y.\]</span></p>
<p>With conditional probabilities introduced, we now have a new (and equivalent) definition of independence:</p>
<p><span class="math display">\[\begin{align}
P(Y = y \mid X = x) &amp;= \frac{P(Y = y \cap X = x)}{P(X = x)} \\
&amp;= \frac{P(Y = y) \cdot P(X = x)}{P(X = x)} \\
&amp;= P(Y = y),
\end{align}\]</span></p>
<p>and likewise, if you switch <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>. Intuitively, this says that knowing <span class="math inline">\(X\)</span> tells you nothing about <span class="math inline">\(Y\)</span>, and knowing <span class="math inline">\(Y\)</span> tells you nothing about <span class="math inline">\(X\)</span>.</p>
</section><section id="law-of-total-probabilityexpectation" class="level3" data-number="4.4"><h3 data-number="4.4" class="anchored" data-anchor-id="law-of-total-probabilityexpectation">
<span class="header-section-number">4.4</span> Law of Total Probability/Expectation</h3>
<p>Quite often, we know the conditional distributions. Nonetheless, we do not directly have the marginal distributions. In fact, most regression and Machine Learning models are about seeking <strong>conditional means</strong> (note that <strong>conditional mean</strong> and <strong>conditional expectation</strong> are synonyms).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition of the Law of Total Expectation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> be two random variables. Generally, a marginal mean <span class="math inline">\(\mathbb{E}_Y(Y)\)</span> can be computed from the <strong>conditional means</strong> <span class="math inline">\(\mathbb{E}_Y(Y \mid X = x)\)</span> and the <strong>probabilities of the conditioning variable</strong> <span class="math inline">\(P(X = x)\)</span>.</p>
<p>The formula, known as the <strong>Law of Total Expectation</strong>, is</p>
<p><span id="eq-law-total-expectation"><span class="math display">\[\mathbb{E}_Y(Y) = \sum_x \mathbb{E}_Y(Y \mid X = x) \cdot P(X = x). \tag{4}\]</span></span></p>
<p>Or, it can also be written as:</p>
<p><span id="eq-law-total-expectation-2"><span class="math display">\[\mathbb{E}_Y(Y) = \mathbb{E}_X [\mathbb{E}_Y(Y \mid X)]. \tag{5}\]</span></span></p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>We are omitting the proof of this law since it is out of the scope of the course.</p>
</div>
</div>
<p>In <a href="#eq-law-total-expectation" class="quarto-xref">Equation&nbsp;4</a> and <a href="#eq-law-total-expectation-2" class="quarto-xref">Equation&nbsp;5</a>, we take care to put subscripts on the expected value operator <span class="math inline">\(\mathbb{E}(\cdot)\)</span> to make clear what random variable we are taking an expectation over. This is often a good idea. <strong>Expectations are sums in the case of discrete random variables</strong> (or, as we will see later, <strong>integrals for continuous random variables</strong>). So, just like how we have the little <span class="math inline">\(x\)</span> in a sum or a <span class="math inline">\(dx\)</span> in an integral, we can use a subscript on the <span class="math inline">\(\mathbb{E}\)</span> to be extra clear.</p>
<p>Also, the previous result in <a href="#eq-law-total-expectation" class="quarto-xref">Equation&nbsp;4</a> extends to probabilities:</p>
<p><span class="math display">\[P(Y = y \cap X = x) = P(Y = y \mid X = x) \cdot P(X = x).\]</span></p>
<p>Now, for the ship case of our random variables <span class="math inline">\(\text{LOS}\)</span> <span class="math inline">\(L\)</span> (the condition) and the number of <span class="math inline">\(\text{Gangs}\)</span> <span class="math inline">\(G\)</span>, suppose we have the <strong>conditional means of gang request <span class="math inline">\(G\)</span> GIVEN the length of stay <span class="math inline">\(L\)</span> of a ship</strong> plotted as a model function in <a href="#fig-model-funtion" class="quarto-xref">Figure&nbsp;4</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-model-funtion" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-model-funtion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_lecture-conditional_files/figure-html/fig-model-funtion-1.png" class="img-fluid figure-img" width="1200">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-model-funtion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Model function for the mean gang request conditioned on the length of stay.
</figcaption></figure>
</div>
</div>
</div>
<p>This curve is called a <strong>model function</strong> and is helpful if we want to predict a ship’s daily gang request if we know their <span class="math inline">\(\text{LOS}\)</span>. But what if we want to compute a <strong>marginal expected gang request</strong>? Let us explore how to do this.</p>
<p>Coming from the above plot plus the marginal PMF of <span class="math inline">\(L\)</span>, we have the conditional expectations of gangs requested in <a href="#tbl-cond-exp-gangs" class="quarto-xref">Table&nbsp;12</a>.</p>
<div class="cell">
<div id="tbl-cond-exp-gangs" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cond-exp-gangs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12: Conditional expectations of gangs requested given length of stay.
</figcaption><div aria-describedby="tbl-cond-exp-gangs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: center;">l (Days)</th>
<th style="text-align: center;">E(G | L = l)</th>
<th style="text-align: center;">P(L = l)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">3.1405</td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">2.4128</td>
<td style="text-align: center;">0.35</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">1.9172</td>
<td style="text-align: center;">0.20</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">1.5960</td>
<td style="text-align: center;">0.10</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">1.2735</td>
<td style="text-align: center;">0.10</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Multiplying the last two columns together, and summing, gives us the marginal expectation; i.e., using <a href="#eq-law-total-expectation" class="quarto-xref">Equation&nbsp;4</a>:</p>
<p><span class="math display">\[\mathbb{E}_G(G) = \sum_l \mathbb{E}_G(G \mid L = l) \cdot P(L = l) = 2.3.\]</span></p>
<p>Now, we will start with in-class questions via <a href="https://student.iclicker.com/"><strong>iClicker</strong></a>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 17
</div>
</div>
<div class="callout-body-container callout-body">
<p>Answer <strong>TRUE</strong> or <strong>FALSE</strong>:</p>
<p>In general for two random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, <span class="math inline">\(P(X = x \mid Y = y)\)</span> is a normalized probability distribution in the sense that</p>
<p><span class="math display">\[\sum_x P(X = x \mid Y = y) = 1.\]</span></p>
<p><strong>A.</strong> TRUE</p>
<p><strong>B.</strong> FALSE</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 18
</div>
</div>
<div class="callout-body-container callout-body">
<p>Answer <strong>TRUE</strong> or <strong>FALSE</strong>:</p>
<p>In general for two random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, <span class="math inline">\(P(X = x \mid Y = y)\)</span> is a normalized probability distribution in the sense that</p>
<p><span class="math display">\[\sum_y P(X = x \mid Y = y) = 1.\]</span></p>
<p><strong>A.</strong> TRUE</p>
<p><strong>B.</strong> FALSE</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 19
</div>
</div>
<div class="callout-body-container callout-body">
<p>Answer <strong>TRUE</strong> or <strong>FALSE</strong>:</p>
<p>Let <span class="math inline">\(X\)</span> be a random variable with non-zero entropy and <span class="math inline">\(Y\)</span> be a random variable with zero entropy. Then, <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent.</p>
<p><strong>A.</strong> TRUE</p>
<p><strong>B.</strong> FALSE</p>
</div>
</div>
<p>We will solve the below exercise during class (<strong>it is not an iClicker question</strong>):</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 20
</div>
</div>
<div class="callout-body-container callout-body">
<p>Given the marginal probabilities of <span class="math inline">\(L\)</span>, what is the expected gang request <span class="math inline">\(G\)</span> given that the ship captain says they will not be at port any longer than 2 days? In symbols:</p>
<p><span class="math display">\[\mathbb{E}(G \mid L \leq 2).\]</span></p>
<div id="tbl-pmf-LOS" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pmf-LOS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13: Probability mass function (PMF) of length of stay <span class="math inline">\(L\)</span>
</figcaption><div aria-describedby="tbl-pmf-LOS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(L\)</span></th>
<th style="text-align: center;"><span class="math inline">\(P(L = l)\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.35</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.2</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">0.1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>You would also need the joint distribution between <span class="math inline">\(L\)</span> and <span class="math inline">\(G\)</span>.</p>
<div class="cell">
<div id="tbl-joint-pmf-gangs-los-3" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-joint-pmf-gangs-los-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14: Joint probability mass function (PMF) for the number of Gangs (G) and length of stay (L) in days.
</figcaption><div aria-describedby="tbl-joint-pmf-gangs-los-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 1</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 2</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 3</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">G = 4</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 1</td>
<td style="text-align: center;">0.0017</td>
<td style="text-align: center;">0.0425</td>
<td style="text-align: center;">0.1247</td>
<td style="text-align: center;">0.0811</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 2</td>
<td style="text-align: center;">0.0266</td>
<td style="text-align: center;">0.1698</td>
<td style="text-align: center;">0.1360</td>
<td style="text-align: center;">0.0176</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 3</td>
<td style="text-align: center;">0.0511</td>
<td style="text-align: center;">0.1156</td>
<td style="text-align: center;">0.0320</td>
<td style="text-align: center;">0.0013</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 4</td>
<td style="text-align: center;">0.0465</td>
<td style="text-align: center;">0.0474</td>
<td style="text-align: center;">0.0059</td>
<td style="text-align: center;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em; font-weight: bold; border-right: 1px solid;">L = 5</td>
<td style="text-align: center;">0.0740</td>
<td style="text-align: center;">0.0246</td>
<td style="text-align: center;">0.0014</td>
<td style="text-align: center;">0.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</div>
</div>
</section></section><section id="conditional-independence" class="level2" data-number="5"><h2 data-number="5" class="anchored" data-anchor-id="conditional-independence">
<span class="header-section-number">5</span> Conditional Independence</h2>
<p>So far, we have discussed the notions of independence and conditional probabilities. We have already discussed conditional distributions such as <span class="math inline">\(P(Y \mid X)\)</span>. However, here are a couple of important questions:</p>
<blockquote class="blockquote">
<p>Can the dependence/independence of random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> change if we condition on another random variable <span class="math inline">\(Z\)</span>?</p>
</blockquote>
<blockquote class="blockquote">
<p>If random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent, are they also independent given random variable <span class="math inline">\(Z\)</span>?</p>
</blockquote>
<p>The answer is: <strong>not necessarily!</strong> Independence and conditional independence are two different things. Here is our old definition of independence: <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent if and only if</p>
<p><span id="eq-marginal-independence"><span class="math display">\[P(X = x \cap Y = y) = P(X = x) \cdot P(Y = y). \tag{6}\]</span></span></p>
<p>Below, we provide the formal definition of <strong>conditional independence</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition of Conditional Independence
</div>
</div>
<div class="callout-body-container callout-body">
<p>Random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are conditionally independent given random variable <span class="math inline">\(Z\)</span> if and only if, for any <span class="math inline">\(x\)</span>, <span class="math inline">\(y\)</span> and <span class="math inline">\(z\)</span>,</p>
<p><span id="eq-conditional-independence"><span class="math display">\[P(X = x \cap Y = y \mid Z = z) = P(X = x \mid Z = z) \cdot P(Y = y \mid Z = z). \tag{7}\]</span></span></p>
<p>In short, we drop in “<span class="math inline">\(\mid Z = z\)</span>” everywhere we can in the original definition of independence.</p>
</div>
</div>
<p>Conditional independence <a href="#eq-conditional-independence" class="quarto-xref">Equation&nbsp;7</a> has all the same properties as regular (marginal) independence <a href="#eq-marginal-independence" class="quarto-xref">Equation&nbsp;6</a>, but the intuition is quite different. For one thing, we have to consider <strong>three random variables</strong>, not just two. Let us check a further example.</p>
<p>Let <span class="math inline">\(L\)</span> be a student’s lab grade in DSCI 551, <span class="math inline">\(Q\)</span> be a student’s quiz grade in DSCI 551, and <span class="math inline">\(S\)</span> represents whether the student majored in Statistics in their undergraduate studies. For simplicity, we will consider only Bernoulli random variables, so <span class="math inline">\(L\)</span> and <span class="math inline">\(Q\)</span> will only take on the values “<em>high</em>” and “<em>low</em>” – but everything here also applies to random variables with more than two possible outcomes.</p>
<p>Here is the joint distribution of <span class="math inline">\(L\)</span>, <span class="math inline">\(Q\)</span>, and <span class="math inline">\(S\)</span>:</p>
<div id="tbl-pmf-example-conditional" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pmf-example-conditional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15: Joint probability mass function (PMF) of <span class="math inline">\(L\)</span>, <span class="math inline">\(Q\)</span> and <span class="math inline">\(S\)</span>.
</figcaption><div aria-describedby="tbl-pmf-example-conditional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(\ell\)</span></th>
<th style="text-align: center;"><span class="math inline">\(q\)</span></th>
<th style="text-align: center;"><span class="math inline">\(s\)</span></th>
<th style="text-align: center;"><span class="math inline">\(P(L = \ell \cap Q = q \cap S = s)\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">low</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;">yes</td>
<td style="text-align: center;">0.01</td>
</tr>
<tr class="even">
<td style="text-align: center;">low</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;">yes</td>
<td style="text-align: center;">0.03</td>
</tr>
<tr class="odd">
<td style="text-align: center;">high</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;">yes</td>
<td style="text-align: center;">0.03</td>
</tr>
<tr class="even">
<td style="text-align: center;">high</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;">yes</td>
<td style="text-align: center;">0.09</td>
</tr>
<tr class="odd">
<td style="text-align: center;">low</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;">no</td>
<td style="text-align: center;">0.21</td>
</tr>
<tr class="even">
<td style="text-align: center;">low</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;">no</td>
<td style="text-align: center;">0.21</td>
</tr>
<tr class="odd">
<td style="text-align: center;">high</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;">no</td>
<td style="text-align: center;">0.21</td>
</tr>
<tr class="even">
<td style="text-align: center;">high</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;">no</td>
<td style="text-align: center;">0.21</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Let us answer the first question:</p>
<blockquote class="blockquote">
<p>Are <span class="math inline">\(L\)</span> and <span class="math inline">\(Q\)</span> independent?</p>
</blockquote>
<p>Well, this question has nothing to do with <span class="math inline">\(S\)</span>, so let us <strong>marginalize out</strong> <span class="math inline">\(S\)</span>. In other words, let us compute the distribution <span class="math inline">\(P(L = \ell \cap Q = q)\)</span> for all values of <span class="math inline">\(\ell\)</span> and <span class="math inline">\(q\)</span>. The rules stay the same – we add up the probabilities associated with the different scenarios. For instance:</p>
<p><span class="math display">\[\begin{align}
P(L = \text{high} \cap Q = \text{high}) &amp;= P(L = \text{high} \cap Q = \text{high} \cap S = \text{yes}) + \\
&amp; \qquad P(L = \text{high} \cap Q = \text{high} \cap S = \text{no}) \\
&amp;= 0.09 + 0.21 \\
&amp;= 0.30.
\end{align}\]</span></p>
<p>Doing this for all four cases yields:</p>
<div id="tbl-pmf-example-conditional-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pmf-example-conditional-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;16: Joint probability mass function (PMF) of <span class="math inline">\(L\)</span> and <span class="math inline">\(Q\)</span>.
</figcaption><div aria-describedby="tbl-pmf-example-conditional-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(\ell\)</span></th>
<th style="text-align: center;"><span class="math inline">\(q\)</span></th>
<th style="text-align: center;"><span class="math inline">\(P(L = \ell \cap Q = q)\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">low</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;">0.22</td>
</tr>
<tr class="even">
<td style="text-align: center;">low</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;">0.24</td>
</tr>
<tr class="odd">
<td style="text-align: center;">high</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;">0.24</td>
</tr>
<tr class="even">
<td style="text-align: center;">high</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;">0.30</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Note the probabilities in <a href="#tbl-pmf-example-conditional-2" class="quarto-xref">Table&nbsp;16</a> still add up to 1.</p>
<p>So, are <span class="math inline">\(L\)</span> and <span class="math inline">\(Q\)</span> independent? <strong>Apparently not.</strong> The marginal probabilities are</p>
<p><span class="math display">\[P(L = \text{high}) = 0.54\]</span></p>
<p>and</p>
<p><span class="math display">\[P(Q = \text{high}) = 0.54,\]</span></p>
<p>but</p>
<p><span class="math display">\[P(L = \text{high} \cap Q = \text{high}) = 0.30 \neq 0.54 \times 0.54.\]</span></p>
<p>Rather, <span class="math inline">\(L\)</span> and <span class="math inline">\(Q\)</span> appear to have a mild positive correlation: <em>when the lab grade is high, the quiz grade is a bit more likely to be also high</em>.</p>
<p>Fine, <span class="math inline">\(L\)</span> and <span class="math inline">\(Q\)</span> are not independent.</p>
<blockquote class="blockquote">
<p>But, what about <span class="math inline">\(L\)</span> and <span class="math inline">\(Q\)</span> given <span class="math inline">\(S\)</span>? Are they conditionally independent?</p>
</blockquote>
<p>As we will see, yes, they are. But before we get to the math, let us discuss the intuition. As we saw above, when the lab grade is high, the quiz grade is a bit more likely to be also high. Why does this happen? In this example, when the lab grade is more likely to be high, that indicates that maybe this person is a Statistics major (a high-scorer, in other words); if so, that means their quiz grade would also be higher.</p>
<p>Now, here is the tricky part: because of the way I carefully crafted this joint distribution, the above reasoning is the <strong>only reason</strong> why high lab grades are associated with high quiz grades. <strong>If you already know that a person is (or is not) a Statistics major, then their lab and quiz grades are completely independent.</strong> This is <strong>conditional independence</strong>.</p>
<p>Like marginal independence, conditional independence is determined entirely by the joint distribution; it is not a property that you can specify separately from the joint. Thus, let us dig into the joint. What we want to know is whether</p>
<p><span class="math display">\[P(L = \ell \cap Q=q \mid S = s) = P(L = \ell \mid S = s) \cdot P(Q = q \mid S = s).\]</span></p>
<p>We would need the corresponding conditional distributions <span class="math inline">\(P(L = \ell \mid S = s)\)</span> and <span class="math inline">\(P(Q = q \mid S = s)\)</span>. Thus, we will check this for both <span class="math inline">\(S = \text{yes}\)</span> and <span class="math inline">\(S = \text{no}\)</span>.</p>
<p>When <span class="math inline">\(S = \text{yes}\)</span>, we have:</p>
<div id="tbl-pmf-example-conditional-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pmf-example-conditional-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;17: First step to obtain the joint probability mass function (PMF) of <span class="math inline">\(L\)</span> and <span class="math inline">\(Q\)</span> given <span class="math inline">\(S = \text{yes}\)</span>.
</figcaption><div aria-describedby="tbl-pmf-example-conditional-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(\ell\)</span></th>
<th style="text-align: center;"><span class="math inline">\(q\)</span></th>
<th style="text-align: center;"><span class="math inline">\(P(L = \ell \cap Q = q \cap S = \text{yes})\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">low</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;">Used to be <span class="math inline">\(0.01\)</span> in the three-variable PMF</td>
</tr>
<tr class="even">
<td style="text-align: center;">low</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;">Used to be <span class="math inline">\(0.03\)</span> in the three-variable PMF</td>
</tr>
<tr class="odd">
<td style="text-align: center;">high</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;">Used to be <span class="math inline">\(0.03\)</span> in the three-variable PMF</td>
</tr>
<tr class="even">
<td style="text-align: center;">high</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;">Used to be <span class="math inline">\(0.09\)</span> in the three-variable PMF</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Now, using the formula approach for a conditional probability, we need the following to get the corresponding conditional distribution given <span class="math inline">\(S = \text{yes}\)</span>:</p>
<p><span class="math display">\[\begin{align}
P(L = \ell \cap Q = q \mid S = \text{yes}) &amp;= \frac{P(L = \ell \cap Q = q \cap S = \text{yes})}{P(S = \text{yes})} \\
\\
&amp; \qquad \qquad \qquad \text{for} \quad \ell = \text{low}, \text{high} \quad \text{and} \quad q = \text{low}, \text{high.}
\end{align}\]</span></p>
<p>From the original three-variable PMF in <a href="#tbl-pmf-example-conditional" class="quarto-xref">Table&nbsp;15</a>, we know that:</p>
<p><span class="math display">\[\begin{align}
P(S = \text{yes}) &amp;= P(L = \text{low} \cap Q = \text{low} \cap S = \text{yes}) + \\
&amp; \qquad P(L = \text{low} \cap Q = \text{high} \cap S = \text{yes}) + \\
&amp; \quad \qquad P(L = \text{high} \cap Q = \text{low} \cap S = \text{yes}) + \\
&amp; \quad  \quad \qquad P(L = \text{high} \cap Q = \text{high} \cap S = \text{yes}) \\
&amp;= 0.01 + 0.03 + 0.03 + 0.09 \\
&amp;= 0.16.
\end{align}\]</span></p>
<p>Therefore, re-normalizing yields:</p>
<div id="tbl-pmf-example-conditional-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pmf-example-conditional-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;18: Re-normalized joint probability mass function (PMF) of <span class="math inline">\(L\)</span> and <span class="math inline">\(Q\)</span> given <span class="math inline">\(S = \text{yes}\)</span>.
</figcaption><div aria-describedby="tbl-pmf-example-conditional-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(\ell\)</span></th>
<th style="text-align: center;"><span class="math inline">\(q\)</span></th>
<th style="text-align: center;"><span class="math inline">\(P(L = \ell \cap Q = q \mid S = \text{yes})\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">low</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;"><span class="math inline">\(0.01 / 0.16 = 0.0625\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">low</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;"><span class="math inline">\(0.03 / 0.16 = 0.1875\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">high</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;"><span class="math inline">\(0.03 / 0.16 = 0.1875\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">high</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;"><span class="math inline">\(0.09 / 0.16 = 0.5625\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>We can check that this conditional distribution on <span class="math inline">\(S = \text{yes}\)</span> satisfies the definition of independence; i.e.,</p>
<p><span class="math display">\[\begin{gather}
P(L = \text{low} \cap Q = \text{low} \mid S = \text{yes}) = \frac{0.01}{0.16} = 0.0625 \\
P(L = \text{low} \cap Q = \text{high} \mid S = \text{yes}) = \frac{0.03}{0.16} = 0.1875 \\
P(L = \text{high} \cap Q = \text{low} \mid S = \text{yes}) = \frac{0.03}{0.16} = 0.1875 \\
P(L = \text{high} \cap Q = \text{high} \mid S = \text{yes}) = \frac{0.09}{0.16} = 0.5625
\end{gather}\]</span></p>
<p>should be the respective products of</p>
<p><span class="math display">\[\begin{align}
P(L = \text{low} \mid S = \text{yes}) \cdot P(Q = \text{low} \mid S = \text{yes})
&amp;= \left( \frac{0.01}{0.16} + \frac{0.03}{0.16} \right) \left( \frac{0.01}{0.16} + \frac{0.03}{0.16}  \right) \\
&amp;= \left( \frac{0.04}{0.16} \right) \left( \frac{0.04}{0.16} \right) \\
&amp;= 0.0625 \\
&amp;= P(L = \text{low} \cap Q = \text{low} \mid S = \text{yes})
\end{align}\]</span></p>
<p><span class="math display">\[\begin{align}
P(L = \text{low} \mid S = \text{yes}) \cdot P(Q = \text{high} \mid S = \text{yes})
&amp;= \left( \frac{0.01}{0.16} + \frac{0.03}{0.16} \right) \left( \frac{0.03}{0.16} + \frac{0.09}{0.16}  \right) \\
&amp;= \left( \frac{0.04}{0.16} \right) \left( \frac{0.12}{0.16} \right) \\
&amp;= 0.1875 \\
&amp;= P(L = \text{low} \cap Q = \text{high} \mid S = \text{yes})
\end{align}\]</span></p>
<p><span class="math display">\[\begin{align}
P(L = \text{high} \mid S = \text{yes}) \cdot P(Q = \text{low} \mid S = \text{yes})
&amp;= \left( \frac{0.03}{0.16} + \frac{0.09}{0.16} \right) \left( \frac{0.01}{0.16} + \frac{0.03}{0.16}  \right) \\
&amp;= \left( \frac{0.12}{0.16} \right) \left( \frac{0.04}{0.16} \right) \\
&amp;= 0.1875 \\
&amp;= P(L = \text{high} \cap Q = \text{low} \mid S = \text{yes})
\end{align}\]</span></p>
<p><span class="math display">\[\begin{align}
P(L = \text{high} \mid S = \text{yes}) \cdot P(Q = \text{high} \mid S = \text{yes})
&amp;= \left( \frac{0.03}{0.16} + \frac{0.09}{0.16} \right) \left( \frac{0.03}{0.16} + \frac{0.09}{0.16}  \right) \\
&amp;= \left( \frac{0.12}{0.16} \right) \left( \frac{0.12}{0.16} \right) \\
&amp;= 0.5625 \\
&amp;= P(L = \text{high} \cap Q = \text{high} \mid S = \text{yes}).
\end{align}\]</span></p>
<p>Using the formula approach for a conditional probability, we need the following to get the corresponding conditional distribution given <span class="math inline">\(S = \text{no}\)</span>:</p>
<p><span class="math display">\[\begin{align}
P(L = \ell \cap Q = q \mid S = \text{no}) &amp;= \frac{P(L = \ell \cap Q = q \cap S = \text{no})}{P(S = \text{no})} \\
\\
&amp; \qquad \qquad \qquad \text{for} \quad \ell = \text{low}, \text{high} \quad \text{and} \quad q = \text{low}, \text{high.}
\end{align}\]</span></p>
<p>When <span class="math inline">\(S = \text{no}\)</span>, we have:</p>
<div id="tbl-pmf-example-conditional-5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pmf-example-conditional-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;19: First step to obtain the joint probability mass function (PMF) of <span class="math inline">\(L\)</span> and <span class="math inline">\(Q\)</span> given <span class="math inline">\(S = \text{no}\)</span>.
</figcaption><div aria-describedby="tbl-pmf-example-conditional-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(\ell\)</span></th>
<th style="text-align: center;"><span class="math inline">\(q\)</span></th>
<th style="text-align: center;"><span class="math inline">\(P(L = \ell \cap Q = q \cap S = \text{no})\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">low</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;">Used to be <span class="math inline">\(0.21\)</span> in the three-variable PMF</td>
</tr>
<tr class="even">
<td style="text-align: center;">low</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;">Used to be <span class="math inline">\(0.21\)</span> in the three-variable PMF</td>
</tr>
<tr class="odd">
<td style="text-align: center;">high</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;">Used to be <span class="math inline">\(0.21\)</span> in the three-variable PMF</td>
</tr>
<tr class="even">
<td style="text-align: center;">high</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;">Used to be <span class="math inline">\(0.21\)</span> in the three-variable PMF</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>From the original three-variable PMF, we know that:</p>
<p><span class="math display">\[\begin{align}
P(S = \text{no}) &amp;= P(L = \text{low} \cap Q = \text{low} \cap S = \text{no}) + \\
&amp; \qquad P(L = \text{low} \cap Q = \text{high} \cap S = \text{no}) + \\
&amp; \qquad \quad P(L = \text{high} \cap Q = \text{low} \cap S = \text{no}) + \\
&amp;\qquad \quad \quad P(L = \text{high} \cap Q = \text{high} \cap S = \text{no}) \\
&amp;= 0.21 + 0.21 + 0.21 + 0.21 \\
&amp;= 0.84.
\end{align}\]</span></p>
<p>Therefore, re-normalizing yields:</p>
<div id="tbl-pmf-example-conditional-6" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pmf-example-conditional-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20: Re-normalized joint probability mass function (PMF) of <span class="math inline">\(L\)</span> and <span class="math inline">\(Q\)</span> given <span class="math inline">\(S = \text{no}\)</span>.
</figcaption><div aria-describedby="tbl-pmf-example-conditional-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead><tr class="header">
<th style="text-align: center;"><span class="math inline">\(\ell\)</span></th>
<th style="text-align: center;"><span class="math inline">\(q\)</span></th>
<th style="text-align: center;"><span class="math inline">\(P(L = \ell \cap Q = q \mid S = \text{no})\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">low</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;"><span class="math inline">\(0.21 / 0.84 = 0.25\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">low</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;"><span class="math inline">\(0.21 / 0.84 = 0.25\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">high</td>
<td style="text-align: center;">low</td>
<td style="text-align: center;"><span class="math inline">\(0.21 / 0.84 = 0.25\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">high</td>
<td style="text-align: center;">high</td>
<td style="text-align: center;"><span class="math inline">\(0.21 / 0.84 = 0.25\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>We can check that this conditional distribution on <span class="math inline">\(S = \text{no}\)</span> satisfies the definition of independence; i.e.,</p>
<p><span class="math display">\[\begin{gather}
P(L = \text{low} \cap Q = \text{low} \mid S = \text{no}) = \frac{0.21}{0.84} = 0.25 \\
P(L = \text{low} \cap Q = \text{high} \mid S = \text{no}) = \frac{0.21}{0.84} = 0.25 \\
P(L = \text{high} \cap Q = \text{low} \mid S = \text{no}) = \frac{0.21}{0.84} = 0.25 \\
P(L = \text{high} \cap Q = \text{high} \mid S = \text{no}) = \frac{0.21}{0.84} = 0.25 \\
\end{gather}\]</span></p>
<p>should be the respective products of</p>
<p><span class="math display">\[\begin{align}
P(L = \text{low} \mid S = \text{no}) \cdot P(Q = \text{low} \mid S = \text{no})
&amp;= \left( \frac{0.21}{0.84} + \frac{0.21}{0.84} \right) \left( \frac{0.21}{0.84} + \frac{0.21}{0.84}  \right) \\
&amp;= \left( \frac{0.42}{0.84} \right) \left( \frac{0.42}{0.84} \right) \\
&amp;= (0.5) (0.5) \\
&amp;= 0.25 \\
&amp;= P(L = \text{low} \cap Q = \text{low} \mid S = \text{no})
\end{align}\]</span></p>
<p><span class="math display">\[\begin{align}
P(L = \text{low} \mid S = \text{no}) \cdot P(Q = \text{high} \mid S = \text{no})
&amp;= \left( \frac{0.21}{0.84} + \frac{0.21}{0.84} \right) \left( \frac{0.21}{0.84} + \frac{0.21}{0.84}  \right) \\
&amp;= \left( \frac{0.42}{0.84} \right) \left( \frac{0.42}{0.84} \right) \\
&amp;= (0.5) (0.5) \\
&amp;= 0.25 \\
&amp;= P(L = \text{low} \cap Q = \text{high} \mid S = \text{no})
\end{align}\]</span></p>
<p><span class="math display">\[\begin{align}
P(L = \text{high} \mid S = \text{no}) \cdot P(Q = \text{low} \mid S = \text{no})
&amp;= \left( \frac{0.21}{0.84} + \frac{0.21}{0.84} \right) \left( \frac{0.21}{0.84} + \frac{0.21}{0.84}  \right) \\
&amp;= \left( \frac{0.42}{0.84} \right) \left( \frac{0.42}{0.84} \right) \\
&amp;= (0.5) (0.5) \\
&amp;= 0.25 \\
&amp;= P(L = \text{high} \cap Q = \text{low} \mid S = \text{no})
\end{align}\]</span></p>
<p><span class="math display">\[\begin{align}
P(L = \text{high} \mid S = \text{no}) \cdot P(Q = \text{high} \mid S = \text{no})
&amp;= \left( \frac{0.21}{0.84} + \frac{0.21}{0.84} \right) \left( \frac{0.21}{0.84} + \frac{0.21}{0.84}  \right) \\
&amp;= \left( \frac{0.42}{0.84} \right) \left( \frac{0.42}{0.84} \right) \\
&amp;= (0.5) (0.5) \\
&amp;= 0.25 \\
&amp;= P(L = \text{high} \cap Q = \text{high} \mid S = \text{no}).
\end{align}\]</span></p>
<p>Note we can recognize the case when <span class="math inline">\(S = \text{no}\)</span> as two independent Bernoulli trials each with <span class="math inline">\(p = 0.5\)</span>.</p>
<p><strong>Finally, we are done. The lab grade and quiz grade are not independent, but they are conditionally independent given information about whether the student was a Statistics major.</strong></p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is also possible to have the opposite case: two variables that <strong>are</strong> marginally independent, but <strong>not</strong> conditionally independent given a third variable.</p>
<p>A classic example is whether a burglar is robbing your home is independent of whether an earthquake is happening. But, if you condition on the fact that your alarm system is ringing, then these variables actually become dependent. Given the alarm, both robbery and earthquake are somewhat likely. But given the alarm, if a robbery is happening, then an earthquake is probably not happening; and if an earthquake is happening, then a robbery is not happening.</p>
<p>This is sometimes called <strong>explaining away</strong>; if you see the robber, this explains why the alarm is ringing, and “explains away” your suspicion that there might be an earthquake; likewise, if you feel an earthquake, this explains why the alarm is ringing and “explains away” your suspicion that there might be a robbery.</p>
</div>
</div>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/ubc-mds\.github\.io\/DSCI_551_stat-prob-dsci\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
          // default icon
          link.classList.add("external");
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../notes/03_lecture-joint.html" class="pagination-link" aria-label="Lecture 3: Joint Probability">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Lecture 3: Joint Probability</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../notes/05_lecture-continuous.html" class="pagination-link" aria-label="Lecture 5: Continuous Distributions">
        <span class="nav-page-text">Lecture 5: Continuous Distributions</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/UBC-MDS/DSCI_551_stat-prob-dsci/issues" class="toc-action"><i class="bi bi-chat-right"></i>Report an issue</a></li></ul></div></div></div></footer><script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>