---
title: "Lab 2: Ordinal Logistic Regression"
format:
  live-html:
    toc: true
    toc-depth: 4
    number-sections: true
webr:
  packages:
    - carData
    - tidyverse
    - broom
    - scales
    - MASS
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

## Setup {.unnumbered}

We will need to load the following packages before proceeding:

```{webr}
library(carData)
library(tidyverse)
library(broom)
library(scales)
library(MASS)
```

## The World Values Surveys {.unnumbered}

One of the advantages of using models such as Ordinal Logistic regression is their suitability to address Social Sciences-related data where encountering discrete and ordinal variables is quite common (e.g., Likert scales!). That said, let us dig into the World Values Surveys (`WVS`) dataset from package `carData`. According to the corresponding documentation, this is the description of the data frame `WVS`:

> *Data from the World Values Surveys 1995-1997 for Australia, Norway, Sweden, and the United States.*

```{webr}
#| autorun: true
#| message: false
#| warning: false
data(WVS)
head(WVS)
tail(WVS)
```

::: {.callout-caution}
## Main Statistical Inquiries
Suppose we are Data Scientists interested in untangling the differences in people's views concerning their government's efforts to fight poverty in Australia, Norway, Sweden, and USA. Hence, **statistically speaking**, we are interested in determining the following:

- Is age of a person a significant factor in these views? Can we quantify this association? If so, by how much?
- Is the country a significant factor in these views? Can we quantify this association? If so, by how much?
:::

## Data Collection and Wrangling {.unnumbered}

We have a **training set size $n = 5381$** subjects:

```{webr}
#| autorun: true
#| message: false
#| warning: false
training_WVS <- WVS
nrow(WVS)
```

We will specifically work on the following columns:

- `poverty`: The answer to the question: "*do you think that what the government is doing for people in poverty in this country is about the right amount, too much, or too little?*"
- `age`: Subject's age in years.
- `country`: Subject's country (`Australia`, `Norway`, `Sweden`, or `USA`).

Hence, let us select the columns of interest in `training_WVS`:

```{webr}
#| autorun: true
#| message: false
#| warning: false
training_WVS <- training_WVS |>
  dplyr::select(poverty, age, country)

head(training_WVS)
tail(training_WVS)
```

## Q1.1. Exploratory Data Analysis {.unnumbered}

Based on our main statistical inquiries, let us answer the following:

**Q1.1.1.** What is our response of interest? 

**Q1.1.2.** What is the response's nature?

**Q1.1.3.** What are our explanatory variables of interest? 

**Q1.1.4.** What is the nature of the explanatory variables?

::: {.callout-note collapse="false"}
## Answers
Available for MDS students.
:::

Now, let us code suitable plots comparing `age` on the $y$-axis by each level in `poverty` on the $x$-axis, which has to be facetted by `country`:

```{webr}
#| autorun: true
#| message: false
#| warning: false
#| fig-height: 10
#| fig-width: 12.5
age_boxplots <- WVS |>
  ggplot(aes(poverty, age)) +
  geom_boxplot(aes(fill = poverty)) +
  scale_fill_brewer(palette = "BuPu") +
  labs(y = "Age(Years)", x = "Government Efforts") +
  facet_wrap(. ~ country) +
  ggtitle("Views on Government Efforts to Fight Poverty by Age and Country") +
  theme(
    plot.title = element_text(size = 24, face = "bold"),
    axis.text = element_text(size = 17),
    axis.title = element_text(size = 21, face = "bold"),
    strip.text = element_text(size = 21),
    legend.position = "none"
  )
age_boxplots
```

**Q1.1.5.** What do you observe about the relationship of `age` and `country` on `poverty`?

::: {.callout-note collapse="false"}
## Answer
Available for MDS students.
:::

Now, let us explore the relationship between `poverty` and `country` via **stacked bar charts**:

```{webr}
#| autorun: true
#| message: false
#| warning: false
#| fig-height: 10
#| fig-width: 12.5
WVS_prop_summary <- as.data.frame(xtabs(
  ~ country +
    poverty,
  WVS
) / rowSums(xtabs(
  ~ country + poverty,
  WVS
)), responseName = "prop")

WVS_prop_summary

WVS_stacked_bars <- ggplot(WVS_prop_summary, aes(x = country, y = prop, fill = poverty)) +
  geom_bar(
    stat = "identity", width = 0.7, colour = "black",
    position = position_fill(reverse = TRUE)
  ) +
  geom_text(
    aes(label = ifelse(prop >= 0.05,
      paste0(sprintf("%.0f", prop * 100), "%"), ""
    )),
    position = position_fill(reverse = TRUE, vjust = 0.5), colour = "firebrick4",
    fontface = "bold", size = 7
  ) +
  scale_y_continuous(labels = percent_format()) +
  labs(y = "Percentage", x = "Country", fill = "") +
  ggtitle("Views on Government Efforts to Fight Poverty by Country") +
  theme(
    plot.title = element_text(size = 24, face = "bold"),
    axis.text.x = element_text(size = 17, angle = 0),
    axis.text.y = element_text(size = 17, angle = 0),
    axis.title = element_text(size = 21),
    legend.text = element_text(size = 21, margin = margin(r = 1, unit = "cm")),
    legend.title = element_text(size = 21, face = "bold")
  ) +
  guides(fill = guide_legend(title = "View", reverse = TRUE)) +
  scale_fill_brewer(palette = "Blues")
WVS_stacked_bars
```

**Q1.1.6.** What do you observe about the relationship of `country` on `poverty`?

::: {.callout-note collapse="false"}
## Answer
Available for MDS students.
:::

## Q1.2. Data Modelling Framework {.unnumbered}

**Q1.2.1.** Having defined the response and explanatory variables in this case, what is the right modelling framework?

::: {.callout-note collapse="false"}
## Answer
Available for MDS students.
:::

**Q1.2.2.** Let us suppose that a given **discrete ordinal response** `poverty` $Y_i$ (for $i = 1, \dots, n$) has categories `Too Little`, `About Right`, and `Too Much` in a training set of size $n$.

::: {.callout-important}
## Important
Categories `Too Little`, `About Right`, and `Too Much` implicate an ordinal scale, i.e., `Too Little` $<$ `About Right` $<$ `Too much`
:::

Moreover, $X_{i, \texttt{age}}$ is a continuous regressor along with the following dummy variables:

$$
X_{i, \texttt{Norway}} =
\begin{cases}
1 \; \; \; \; \text{if the subject is from Norway},\\
0 \; \; \; \; \mbox{otherwise}.
\end{cases}
$$

$$
X_{i, \texttt{Sweden}} =
\begin{cases}
1 \; \; \; \; \text{if the subject is from Sweden},\\
0 \; \; \; \; \mbox{otherwise}.
\end{cases}
$$

$$
X_{i, \texttt{USA}} =
\begin{cases}
1 \; \; \; \; \text{if the subject is from USA},\\
0 \; \; \; \; \mbox{otherwise}.
\end{cases}
$$

::: {.callout-important}
## Important
Note that `Australia` will be the baseline for the variable `country`.
:::

Now, **briefly in plain words**, describe the **two odds** of our chosen modelling framework for the response of interest.

::: {.callout-note collapse="false"}
## Answer
Available for MDS students.
:::

**Q1.2.3.** **Mathematically**, what is the system of modelling equations?

::: {.callout-note collapse="false"}
## Answer
Available for MDS students.
:::

## Q1.3. Estimation {.unnumbered}

Using the corresponding fitting function and `training_WVS`, estimate the corresponding regression model of `poverty` versus `age` and `country`.

::: {.callout-note collapse="false"}
## Answer
```{webr}
#| autorun: true
#| message: false
#| warning: false
# YOUR CODE GOES HERE
```
:::

## Q1.4. Inference {.unnumbered}

Using your fitted model, are the explanatory variables `age` and `country` statistically associated to the response `poverty`? Below, provide the corresponding code to fit your regression model.

::: {.callout-note collapse="false"}
## Answer
```{webr}
#| autorun: true
#| message: false
#| warning: false
# YOUR CODE GOES HERE
```
:::

Now, state your inferential conclusion with a significance level $\alpha = 0.05$.

::: {.callout-note collapse="false"}
## Answer
Available for MDS students.
:::

## Q1.5. Coefficient Interpretation {.unnumbered}

**Q1.5.1.** Obtain the estimates **on the scale of the cumulative odds** via `poverty_model`. Moreover, obtain the corresponding 95% confidence intervals.

::: {.callout-note collapse="false"}
## Answer
```{webr}
#| autorun: true
#| message: false
#| warning: false
# YOUR CODE GOES HERE
```
:::

**Q1.5.2.** Using the cumulative odds associated to the system of equations in **Q1.2.3.**, provide the interpretation for `age` **by each cumulative odd**.

::: {.callout-note collapse="false"}
## Answer
Available for MDS students.
:::

**Q1.5.3.** Using the cumulative odds associated to the system of equations in **Q1.2.3.**, provide the interpretation for `country` (versus the baseline) **by each cumulative odd**.

::: {.callout-note collapse="false"}
## Answer
Available for MDS students.
:::

## Q1.6. Prediction {.unnumbered}

**Going beyond our main statistical inquiries**, use this model to predict the `poverty` view probabilities for an American subject who is 60 years old. Moreover, provide a complete description of this prediction in plain words.

::: {.callout-note collapse="false"}
## Answer
```{webr}
#| autorun: true
#| message: false
#| warning: false
# YOUR CODE GOES HERE
```
:::

How about the Swedish counterpart? Provide the corresponding full description and the necessary code to support this answer.

::: {.callout-note collapse="false"}
## Answer
```{webr}
#| autorun: true
#| message: false
#| warning: false
# YOUR CODE GOES HERE
```
:::
