project:
  type: website
  output-dir: ../docs
  preview:
    port: 54320
    browser: true
  resources:
    - slides/Lecture1
    - slides/Lecture2
    - slides/Lecture3
    - slides/Lecture4
    - slides/Lecture5
    - slides/Lecture6
    - slides/Lecture7
    - slides/Lecture8
    - notes/datasets/college_data.csv
    - notes/datasets/milk_fat.csv
    - notes/datasets/breast_cancer.csv
    - notes/datasets/doordash.csv
    - scripts/support_functions.R
    
  # Only render files explicitly listed here
  render:
    - index.qmd
    - notes/lecture1-glm-link-functions-and-count-regression.qmd
    - notes/lecture2_glm_model_selection_multinomial.qmd
    - notes/lecture3_glm_ordinal_regression.qmd
    - notes/lecture4_linear_mixed_effects_models.qmd
    - notes/lecture5_survival_analysis.qmd
    - notes/lecture6_local_regression.qmd
    - notes/lecture7_quantile_regression.qmd
    - notes/lecture8_missing_data.qmd
    - notes/warmup-lab1.qmd
    - notes/warmup-lab2.qmd
    - notes/warmup-lab3.qmd
    - notes/warmup-lab4.qmd
    - notes/appendix-binary-log-regression.qmd
    - notes/appendix-binary-multivariate-normal.qmd
    - notes/appendix-greek-alphabet.qmd
    - notes/appendix-reg-cheatsheet.qmd
    - notes/appendix-reg-mindmap.qmd
    - notes/appendix-faq.qmd
    - learning-goals.qmd
    - LICENSE.qmd

website:
  title: "DSCI 562: Regression II"
  site-url: https://ubc-mds.github.io/DSCI_562_regr-2
  issue-url: https://github.com/UBC-MDS/DSCI_562_regr-2/issues
  repo-actions: [edit, source, issue]
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    right:
      - icon: github
        href: https://github.com/UBC-MDS/DSCI_562_regr-2
        aria-label: GitHub
    left:
      - href: index.qmd
        text: Home
        
  sidebar:
    logo: notes/img/UBC_MDS_logo.png
    logo-alt: "UBC-MDS Logo Image"
    style: "docked"
    search: true
    contents:
    
      - section: "Lectures"
        contents:
          - learning-goals.qmd
          - notes/lecture1-glm-link-functions-and-count-regression.qmd
          - notes/lecture2_glm_model_selection_multinomial.qmd
          - notes/lecture3_glm_ordinal_regression.qmd
          - notes/lecture4_linear_mixed_effects_models.qmd
          - notes/lecture5_survival_analysis.qmd
          - notes/lecture6_local_regression.qmd
          - notes/lecture7_quantile_regression.qmd
          - notes/lecture8_missing_data.qmd
      - section: "Warmup Lab Exercises"
        contents:
          - notes/warmup-lab1.qmd
          - notes/warmup-lab2.qmd
          - notes/warmup-lab3.qmd
          - notes/warmup-lab4.qmd
      - section: "Appendices"
        contents:
          - notes/appendix-binary-log-regression.qmd
          - notes/appendix-binary-multivariate-normal.qmd
          - notes/appendix-greek-alphabet.qmd
          - notes/appendix-reg-cheatsheet.qmd
          - notes/appendix-reg-mindmap.qmd
          - notes/appendix-faq.qmd
          - LICENSE.qmd

format:
  html:
    css: styles.css
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-expand: 4
    toc-location: right
    code-fold: false
    fontsize: 1.3em
    linestretch: 1.6
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    code-link: true
    number-sections: true
    number-depth: 4
    smooth-scroll: true
    grid:
      sidebar-width: 300px
      body-width: 960px
      margin-width: 275px
      gutter-width: 1.3em
      
  live-html:
    css: styles.css
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-expand: 4
    toc-location: right
    code-fold: false
    fontsize: 1.3em
    linestretch: 1.6
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    code-link: true
    number-sections: true
    number-depth: 4
    smooth-scroll: true
    grid:
      sidebar-width: 300px
      body-width: 960px
      margin-width: 275px
      gutter-width: 1.3em